### ISSUE TITLE
How to generate hg19_tss_info.bed myself or where could it be downloaded

### ISSUE THREAD

**Issue by qianhuiyu** [morris-lab/CellOracle#10]
I would like to run cellOracle on my human scATAC-seq dataset, but I was lost about how to get a hg19 tss_annotated bed file as shown in the example. The bioRxiv paper says it came from HOMER. However, when I checked the webpage of HOMER, HOMER is to annotate where peaks located relative annotated gene regions, and it did not provide TSS annotation. Also, the output of HOMER is different from that of the example shown in cellOracle's tutorial. I also think of taking +-500 bp of the annotated gene start site as the TSS annotation. However, the region length of the example varies gene by gene. That also confuses me how should I get the annotated TSS regions. If the developers could explain how they get their  mm9/10_tss_info.bed in detail, I would be much appreciative. Thanks a lot.

**Comment by KenjiKamimoto-wustl122** [comment]
Hi qianhuiyu,
I uploaded our python custom script that we used for the processing of tss annotation file.
https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/misc/make_tss_referenece_from_homer_data.ipynb
With this script, you can download data from HOMER web database and create tss bed file.
I also uploaded hg19 tss file. Please download hg19 tss bed file with this link below. 
https://github.com/morris-lab/CellOracle/tree/master/celloracle/motif_analysis/tss_ref_data

Instead, you can also load the same file with a celloracle function. Please re-install celloracle and use the function below.
`tss_annotated = ma.get_tss_info(peak_str_list=peaks, ref_genome="hg19")`

**Comment by qianhuiyu** [comment]
Cool! Thanks a lot for your prompt	reply and kindly help!
