### ISSUE TITLE
ValueError in TSS annotation: not enough values to unpack (expected at least 2, got 1)

### ISSUE THREAD

**Issue by Edsan17** [morris-lab/CellOracle#100]
Hey! Could you help me, I know that celloracle supported "hg38", but it says "no". How can I get the tss info then?

I am running: 

tss_annotated = ma.get_tss_info(peak_str_list=peaks, ref_genome='hg38')

But it shows:

ValueError                                Traceback (most recent call last)
Cell In[10], line 4
      1 #Annotate transcription start sites (TSSs)
      2 
      3 ##!! Please make sure to specify the correct reference genome here
----> 4 tss_annotated = ma.get_tss_info(peak_str_list=peaks, ref_genome='hg38')

File /opt/conda/envs/celloracle/lib/python3.8/site-packages/celloracle/motif_analysis/tss_annotation.py:72, in get_tss_info(peak_str_list, ref_genome, verbose, custom_tss_file_path)
     68         **raise ValueError(f"ref_genome: {ref_genome} is not supported in celloracle. See celloracle.motif_analysis.SUPPORTED_REF_GENOME to get supported ref genome list. If you have a request for a new referencce genome, please post an issue in github issue page.")**
     70     ref = _load_tss_ref_data(ref_genome=ref_genome)
---> 72 queue = list_peakstr_to_df(peak_str_list)
     73 queue = BedTool.from_dataframe(queue)
     75 annotated = annotate_tss(tss_ref_bed=ref, queue_bed=queue, verbose=verbose)

File /opt/conda/envs/celloracle/lib/python3.8/site-packages/celloracle/motif_analysis/process_bed_file.py:76, in list_peakstr_to_df(x)
     58 def list_peakstr_to_df(x):
     59     """
     60     Convert list of peaks(str) into data frame.
     61 
   (...)
     74             2	chr1	3119478	3121690
     75     """
---> 76     df = np.array([decompose_chrstr(i) for i in x])
     77     df = pd.DataFrame(df, columns=["chr", "start", "end"])
     78     df["start"] = df["start"].astype(int)

File /opt/conda/envs/celloracle/lib/python3.8/site-packages/celloracle/motif_analysis/process_bed_file.py:76, in <listcomp>(.0)
     58 def list_peakstr_to_df(x):
     59     """
     60     Convert list of peaks(str) into data frame.
     61 
   (...)
     74             2	chr1	3119478	3121690
     75     """
---> 76     df = np.array([decompose_chrstr(i) for i in x])
     77     df = pd.DataFrame(df, columns=["chr", "start", "end"])
     78     df["start"] = df["start"].astype(int)

File /opt/conda/envs/celloracle/lib/python3.8/site-packages/celloracle/motif_analysis/process_bed_file.py:53, in decompose_chrstr(peak_str)
     39 def decompose_chrstr(peak_str):
     40     """
     41     Take peak name as input and return splitted strs.
     42 
   (...)
     51        "chr1", "111111", "222222"
     52     """
---> 53     *chr_, start, end = peak_str.split("_")
     54     chr_ = "_".join(chr_)
     56     return chr_, start, end

**ValueError: not enough values to unpack (expected at least 2, got 1)**

I previously import the libraries:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import os, sys, shutil, importlib, glob
from tqdm.notebook import tqdm 
from celloracle import motif_analysis as ma
import celloracle as co

**Comment by Edsan17** [comment]
Ok, I checked my peaks, and they had "-" instead of "_". I manually edited it and now I have:

array(['chr1_180733_181030', 'chr1_181282_181580', 'chr1_191297_191583',
       ..., 'chrY_19744107_19745290', 'chrY_20574970_20576232',
       'chrY_26670261_26671767'], dtype=object)

However, now my problem is:

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[9], line 4
      1 #Annotate transcription start sites (TSSs)
      2 
      3 ##!! Please make sure to specify the correct reference genome here
----> 4 tss_annotated = ma.get_tss_info(peak_str_list=peaks, ref_genome='hg38')

File /opt/conda/envs/celloracle/lib/python3.8/site-packages/celloracle/motif_analysis/tss_annotation.py:75, in get_tss_info(peak_str_list, ref_genome, verbose, custom_tss_file_path)
     72 queue = list_peakstr_to_df(peak_str_list)
     73 queue = BedTool.from_dataframe(queue)
---> 75 annotated = annotate_tss(tss_ref_bed=ref, queue_bed=queue, verbose=verbose)
     77 return annotated

File /opt/conda/envs/celloracle/lib/python3.8/site-packages/celloracle/motif_analysis/tss_annotation.py:105, in annotate_tss(tss_ref_bed, queue_bed, verbose)
    102     raise ValueError("queue bed file error")
    104 # intersect
--> 105 intersected = tss_ref_bed.intersect(queue_bed, wb=True)
    106 intersected = intersected.to_dataframe()
    108 # change name

File /opt/conda/envs/celloracle/lib/python3.8/site-packages/pybedtools/bedtool.py:923, in BedTool._log_to_history.<locals>.decorated(self, *args, **kwargs)
    919 def decorated(self, *args, **kwargs):
    920 
    921     # this calls the actual method in the first place; *result* is
    922     # whatever you get back
--> 923     result = method(self, *args, **kwargs)
    925     # add appropriate tags
    926     parent_tag = self._tag

File /opt/conda/envs/celloracle/lib/python3.8/site-packages/pybedtools/bedtool.py:244, in _wraps.<locals>.decorator.<locals>.not_implemented_func(*args, **kwargs)
    243 def not_implemented_func(*args, **kwargs):
--> 244     raise NotImplementedError(help_str)

NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

I am working in Jupyter Notebook pulling the docker rnakato/shortcake; I am working in the WahU server. I have no permission to install BEDTools with my user, at least. Should installing BEDTools be enough to make it run? Any suggestions?

**Comment by Edsan17** [comment]
[all_peaks.csv](https://github.com/morris-lab/CellOracle/files/10610756/all_peaks.csv)
This is my edited all peaks, I just replaced "-" with "_" in Notepad.

**Comment by KenjiKamimoto-wustl122** [comment]
@Edsan17 

It seems your environment don't have bedtools as you said.  
I'd like to suggest using our docker image, which already includes celloracle and bedtools. Here is documentation. https://morris-lab.github.io/CellOracle.documentation/installation/docker_additional_information.html

If it is impossible to use our docker image and need to use your environment, please consult with your system manager. I'm sorry but I cannot help about it.
