### ISSUE TITLE
Request for Sus Scrofa genome

### ISSUE THREAD

**Issue by michiste** [morris-lab/CellOracle#101]
Hi,

I'm very interested in applying CellOracle to a pig data set. Thus, I was wondering, if you could add support for Sus Scrofa (Sscrofa11.1) genome? 

Thanks a lot in advance!

**Comment by KenjiKamimoto-wustl122** [comment]
@michiste 

I'm Kenji, a developer of celloracle. Thank you for your interest in our tool!
Yes, I can add data for Sus Scrofa reference.

For that task, please let me confirm the following points.

1. CellOracle internally use `genomepy` to get genome sequence. The following reference genomes are found for Sus Scrofa 11. I think these reference genomes are what you want. Can you please confirm that?
<img width="1030" alt="スクリーンショット 2023-02-06 午後1 31 09" src="https://user-images.githubusercontent.com/42547768/217067082-91d9e0fd-089f-409e-9611-8b9327022286.png">


2. In a celloracle analysis, we need to do transcription starting site (TSS) annotation. And the TSS annotation requires gene annotation data. We typically use ensembl database to get gene annotation. I'm going to use the following gene annotation. Is it OK? If you have another specific gene annotation, please let me know.
https://useast.ensembl.org/Sus_scrofa/Info/Index

**Comment by michiste** [comment]
Hi Kenji,

thanks a lot for your help and the fast reply!

1. Yes, these are the correct references. We use Sscrofa11.1 from Ensembl.
2. Yes, the Ensembl annotations are fine. Would it be possible to use release 101? https://ftp.ensembl.org/pub/release-101/gtf/sus_scrofa/

**Comment by KenjiKamimoto-wustl122** [comment]
@michiste 

Thank you for the information! I will make data using release 101 genome! I think I can find time to do that by next week (or by the end of the month at the latest). I'll let you know when it is ready.

**Comment by michiste** [comment]
@KenjiKamimoto-wustl122  Thanks a lot for the fast update! Highly appreciated!
