### ISSUE TITLE
Transcription factor binding motif scan - danRer11

### ISSUE THREAD

**Issue by mtrebelo** [morris-lab/CellOracle#102]
Hi! I have a zebrafish dataset (ref genome: danRer11)  and I am starting to run CellOracle. 

In the '**transcription factor binding motif scan**', I have reached to '**3. Instantiate TFinfo object and search for TF binding motifs**' and used the motifs 'CisBP_ver2_Danio_rerio.pfm' from CisBP.

When I check the motif scan results through `tfi.scanned_df,` I get a table in which factors_direct and factors_indirect are two empty columns. So, after filtering, when I convert into a dataframe, the result is a table equal to the input one obtained via `peaks = pd.read_csv("processed_peak_file.csv", `index_col=0)`

Is there an issue with the motifs associated with danRer11 or do you have a suggestion on how to obtain the correct base GRN in the end?

Thank you a lot in advance.

**Comment by KenjiKamimoto-wustl122** [comment]
@mtrebelo 
 
I’m Kenji, a developer of the celloracle. I think the issue is caused by the same bug as #99, and solved in the latest version celloracle version 0.10.15. I’m sorry for the inconvenience, but can you please update the celloracle and try motif scan again?
Thanks.
