### ISSUE TITLE
 Consider removing FA2 as a dependency as it is not actively maintained and does not pip install from PyPI on Python 3.9+

### ISSUE THREAD

**Issue by dburkhardt** [morris-lab/CellOracle#104]
**Describe the bug**
To reproduce
1. Have Python 3.9.15
2. Build scenicplus from source
3. Install fails at `fa2` dependency due to https://github.com/bhargavchippada/forceatlas2/issues/34

Workaround:
1. Build fa2 from source
2. Build scenicplus from source

**Error output**
See https://github.com/bhargavchippada/forceatlas2/issues/34

**Additional context**
* Last commit to fa2 is from December 2020 and last release is from Jan 2019
* The lead dev of fa2 acknowledges they are not actively maintaining the package: https://github.com/bhargavchippada/forceatlas2/issues/38
* This was also an issue in `scenicplus` and they removed the dependency: https://github.com/aertslab/scenicplus/issues/92

**Comment by KenjiKamimoto-wustl122** [comment]
@dburkhardt 

Thank you for your feedback.
I'll look into it. 

CellOracle is developed and tested with Python 3.8 and is not currently guaranteed for Python 3.9.
Can you please use python 3.8 for now? But we will test newer version of python including dependencies as soon as possible!

**Comment by dburkhardt** [comment]
Hi Kenji, thanks for the prompt response!

Where is `fa2` used in the code base? I don't see it when I search.

Regarding `3.8`, this is now an [outdated release](https://www.python.org/downloads/release/python-380/) for Python. The current stable release is `3.9`. If this is the only thing keeping you using an outdated release, why not remove?

**Comment by KenjiKamimoto-wustl122** [comment]
The force-directed graph is used in our tutorial preparing celloracle input data.

https://morris-lab.github.io/CellOracle.documentation/notebooks/03_scRNA-seq_data_preprocessing/scanpy_preprocessing_with_Paul_etal_2015_data.html

**Comment by dburkhardt** [comment]
If it's just in the tutorial for pre-processing scRNA, why not just ask people to install it in the notebook like you do with the ATAC base-grn pre-processing?

It's not really required to use CellOracle, right?

**Comment by KenjiKamimoto-wustl122** [comment]
Yes, it is not CellOracle itself, but the scRNA-seq data preparation step is a necessary step, and I'm keeping it.

The fa2 is not the reason why use python3.8. We are working hard to update the package, but it is always taking time to keep python's latest release. Can you please use python 3.8 for now? We will test the newer version of python, including dependencies, as soon as possible.
Do you have any problem with python3.8?

**Comment by dburkhardt** [comment]
Great! For reference, I'm using CellOracle on Python 3.9.15 and it works fine.
