### ISSUE TITLE
[Enhancement] Make `estimate_transition_prob` more scaleable

### ISSUE THREAD

**Issue by dburkhardt** [morris-lab/CellOracle#108]
Right now, `estimate_transition_prob`seems to be the least scaleable component of the CellOracle pipeline, and it limits the feasibility of systematic perturbation experiments on larger datasets. It seems like for a 90,000 cell dataset, even 2TB of RAM is insufficient.

https://github.com/morris-lab/CellOracle/blob/7cfc7ca4e17e828ce7a0f4d808f8dfaa68df2f83/celloracle/trajectory/modified_VelocytoLoom_class.py#L262-L401

I tried stepping through the function manually, and it looks like the real issue is the `colDeltaCorpartial` or `colDeltaCor` functions that were copied over from Velocyto (which hasn't been maintained since 2019).   

https://velocyto.org/velocyto.py/fullapi/api_estimation.html#velocyto.estimation.colDeltaCorpartial

Is this something you've noticed @KenjiKamimoto-wustl122 ?

**Comment by KenjiKamimoto-wustl122** [comment]
@dburkhardt 

Yes, you're totally right. This part is the most memory-consuming part, and I guess it requires memory in an O(n^2) manner on the number of cells. 
I've noticed this. As a solution, I recommend subsampling data into 30k cells if your data have many cells. https://morris-lab.github.io/CellOracle.documentation/notebooks/04_Network_analysis/Network_analysis_with_Paul_etal_2015_data.html#1.-Load-data

Maybe we can do refactoring this function in the future, but I don't have enough time so far. I'd appreciate it if you let me know an idea for the alternative emory efficient method that substitutes `colDeltaCorpartial`.

**Comment by KenjiKamimoto-wustl122** [comment]
Because I don't have good idea to do this task, we cannot announce specific plan for this.
Let me close the issue.
