### ISSUE TITLE
Creating gradient object using RNA-Velocity data instead of pseudotime in TF perturbations step

### ISSUE THREAD

**Issue by nitinnarwade** [morris-lab/CellOracle#109]
Thank you so much for this wonderful package. I am thoroughly enjoying using it.

Could you please provide some tutorial or hint for using RNA-velocity information to compare simulation vectors with development vectors in the TF perturbations step? In short could you please suggest a way to create a gradient object using RNA-velocity data instead of pseudotime?

Thanks and Regards,
Nitin N.

**Comment by nitinnarwade** [comment]
For now I am copying the settings (`gradient.cell_idx_use, gradient.embedding, gradient.gridpoints_coordinates, gradient.mass_filter, gradient.n_grid, gradient.n_neighbors, gradient.total_p_mass, gradient.smooth, gradient.ref_flow`) required for dot product calculation from velocyto object to the gradient object. Then performing calculate_inner_product()
 and calculate_digitized_ip steps. @KenjiKamimoto-wustl122 Does it make sense?

Thanks in advance :)
Regards,
Nitin N.

**Comment by KenjiKamimoto-wustl122** [comment]
@nitinnarwade 

Thank you for the great suggestion.
I'm sorry I cannot find time to do that task now because of lack of time.
But I may try to add some notebook in the future.

**Comment by nitinnarwade** [comment]
Thank you so much. 

Regards,
Nitin N.
