### ISSUE TITLE
checking_installation: rnetcarto -> NG

### ISSUE THREAD

**Issue by doctorxie** [morris-lab/CellOracle#11]
I already install the rnetcarto package by using install.packages("rnetcarto"). And I can libarry(rnetcarto). But when enter the python to check the library. It put the error.
Error in library(rnetcarto) : there is no package called ‘rnetcarto’
Execution halted
Build process aborts.
checking_installation: rnetcarto -> NG
 R library, rnetcarto is unavailable. Please check installation. 

I switch the R version 3.5.3 to version 3.6.2, and install all the dependent R packages including rnetcarto. But it still put the same error.

**Comment by KenjiKamimoto-wustl122** [comment]
I guess your R path was not correctly recognized. Such problem can happen if your system have multiple R environments. 

Could you please check R path in your system according to the following instructions?

Step 1) Please check the R path that you are trying to use.
In general, you can check file path if you run the following code **in your R console**.
`R.home("bin/R")`


Step 2) Please update celloracle (version>=0.3.4) and run the following command **in Jupyter notebook**.  
You'll get R path that was recognized by your python system.
`import celloracle as co`
`co.network_analysis.get_R_path()`

I guess the R path that you got in step2 was different from R path that you got in the step1.

Step3) You can set your correct R path for celloracle analysis by the following function.
`co.network_analysis.set_R_path(R_path)`

For example, if your R-path that you got in step1 was  /usr/local/bin/R,
Please run the following command  **in Jupyter notebook**.
`co.network_analysis.set_R_path("/usr/local/bin/R")`

Step4) Please check R-installation again. Hopefully it will work.
`co.network_analysis.test_R_libraries_installation()`

**Comment by doctorxie** [comment]
Many thanks. It solves my problem when I update the celloracle .
