### ISSUE TITLE
Error in tfi.scan motif scan output - missing factors 

### ISSUE THREAD

**Issue by Mesi395** [morris-lab/CellOracle#121]
Hello, 

When running the tfi.scan function with zebrafish motifs from the CisBP database, I get an output table with empty columns for the TFs associated to each motif. 

motifs = ma.load_motifs("CisBP_ver2_Danio_rerio.pfm")

tfi.scan(fpr=0.02, n_cpus=45, motifs=motifs, verbose=True)

tfi.scanned_df.head()

<img width="623" alt="image" src="https://user-images.githubusercontent.com/44529856/227227634-d944e550-931c-49f5-9e92-d469e20915c7.png">

Can you please advise how to resolve this issue? 

Thank you!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi @Mesi395 

Sorry, this is a bug in old version. Can you please reinstall CellOracle and try again?
For more information, please see #102 

Let me close the issue as I think it is solved. But please re-open the issue if you still have the error on the current version of CellOracle.

**Comment by Mesi395** [comment]
Dear Mr Kamimoto,

Thank you for your response. I updated CO as you suggested and it works
well now. Thanks!

Best regards,
Emi
