### ISSUE TITLE
Pointing out typos in filenames and the documentation

### ISSUE THREAD

**Issue by Naoto-Yamaguchi** [morris-lab/CellOracle#13]
Hi, I'm Naoto Yamaguchi from the University of Tokyo.
I enjoyed reading your paper and watching the CellOracle workshop video on YouTube!!

I found some trivial typos **_in your filenames_**.
- CellOracle/docs/notebooks/04_Network_analysis/Network_analysis_**with_with**\_Paul_etal_2015_data.ipynb
→Network_analysis\_**with**_Paul_etal_2015_data.ipynb

- CellOracle/docs/notebooks/05_simulation/Gata1_KO_simulation_**with_with**\_Paul_etal_2015_data.ipynb
→Gata1_KO_simulation\_**with**_Paul_etal_2015_data.ipynb

- CellOracle/celloracle/data_conversion/process_**srurat**\_object.py
→process\_**seurat**_object.py

---
In addition, I found some format errors **_in the documentation_**.
- indent is required in the table of content
2. Transcription factor binding motif scan
3.1 check reference genome installation
https://morris-lab.github.io/CellOracle.documentation/tutorials/motifscan.html

- There are some duplicate section numbers
3. Single-cell RNA-seq data preprocessing
A. scRNA-seq data preprocessing with scanpy
(8. Check data / 8. Make annotation for cluster)
https://morris-lab.github.io/CellOracle.documentation/tutorials/scrnaprocess.html#a-scrna-seq-data-preprocessing-with-scanpy

4. Network analysis
 (4. Save and Load. / 4. GRN calculation)
https://morris-lab.github.io/CellOracle.documentation/tutorials/networkanalysis.html

- section number is missing
5. Simulation with GRNs
(section 5.2 is missing)
https://morris-lab.github.io/CellOracle.documentation/tutorials/simulation.html

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Naoto,
Thank you for reading our paper and pointing out typos! I'll fix them asap!

**Comment by KenjiKamimoto-wustl122** [comment]
Documentation was updated now.
