### ISSUE TITLE
Docker pull command error

### ISSUE THREAD

**Issue by dyl4nm4rsh4ll** [morris-lab/CellOracle#137]
Hi, I am going through the [Cell Oracle tutorial](https://morris-lab.github.io/CellOracle.documentation/installation/index.html). I tried to use the Docker Image but encountered the following error:

```> sudo docker pull kenjikamimoto126/celloracle_ubuntu:latest```
```Error response from daemon: manifest for kenjikamimoto126/celloracle_ubuntu:latest not found: manifest unknown: manifest unknown```

It looks like the image is not available? 
```> sudo docker search kenjikamimoto126/celloracle_ubuntu```
```NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED```

Looking forward to getting this thing running!

**Comment by KenjiKamimoto-wustl122** [comment]
@dyl4nm4rsh4ll 

Sorry for the error! The correct docker image tag is `kenjikamimoto126/celloracle_ubuntu:0.12.0`.

 I updated tutorial page.

**Comment by dyl4nm4rsh4ll** [comment]
Heads up, the docker run command had to be slightly modified as well. 

docker run -dit \
  --name celloracle_container \
  -p 8888:8888 \
  -v $(pwd)/data_folder:/root/data_folder \
  `kenjikamimoto126/`celloracle_ubuntu:0.12.0
