### ISSUE TITLE
monocle/monocle3 compatibility issues

### ISSUE THREAD

**Issue by cartal** [morris-lab/CellOracle#14]
Hi @KenjiKamimoto-wustl122 ,

I have tried to update my `cicero` processed data but since I updated the latest version of `celloracle` and I run the following command:

```
input_cds <-  suppressWarnings(newCellDataSet(indata,
                            phenoData = pd,
                            featureData = fd,
                            expressionFamily=VGAM::binomialff(),
                            lowerDetectionLimit=0))
```

I keep having the following error:

```
Error in newCellDataSet(indata, phenoData = pd, featureData = fd, expressionFamily = VGAM::binomialff(), : could not find function "newCellDataSet"
Traceback:

1. suppressWarnings(newCellDataSet(indata, phenoData = pd, featureData = fd, 
 .     expressionFamily = VGAM::binomialff(), lowerDetectionLimit = 0))
2. withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
```

I know this has to do with compatibility with `monocle3` so I went and installed `monocle`. Then it works until I run this function:
```
input_cds <- preprocessCDS(input_cds, norm_method = "none")
```

and I get the following error: 

```
Error in preprocessCDS(input_cds, norm_method = "none"): could not find function "preprocessCDS"
```

I have tried to install `celloracle` from scratch in a different machine and  get the same error. Do you know what the issue may be?

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Carlos,

I think we did not use the function, "preprocessCDS" in our tutorial or celloracle code.

**Comment by cartal** [comment]
Maybe I'm using an outdated version of the tutorial?

The code I run is this:

```
set.seed(2017)

input_cds <- detectGenes(input_cds)
input_cds <- estimateSizeFactors(input_cds)

input_cds <- preprocessCDS(input_cds, norm_method = "none")
input_cds <- reduceDimension(input_cds, max_components = 2, verbose = T, scaling = FALSE, relative_expr = FALSE,
                      reduction_method = 'tSNE', norm_method = "none")

tsne_coords <- t(reducedDimA(input_cds))
row.names(tsne_coords) <- row.names(pData(input_cds))
cicero_cds <- make_cicero_cds(input_cds, reduced_coordinates = tsne_coords)
```

**Comment by KenjiKamimoto-wustl122** [comment]
Although I'm not sure about the problem, anyway you do not need the function "preprocessCDS " in our tutorial.
Please use our tutorial.
https://morris-lab.github.io/CellOracle.documentation/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/01_atacdata_to_cicero.html

**Comment by cartal** [comment]
Hi @KenjiKamimoto-wustl122 , I was using your tutorial almost verbatim :) but I have realised now that it has been updated. So now I have used the latest version, like this:

```
set.seed(2017)

input_cds <- detectGenes(input_cds)
input_cds <- estimateSizeFactors(input_cds)

input_cds <- reduceDimension(input_cds, max_components = 2, verbose = T, scaling = FALSE, relative_expr = FALSE,
                      reduction_method = 'tSNE', norm_method = "none")

tsne_coords <- t(reducedDimA(input_cds))
row.names(tsne_coords) <- row.names(pData(input_cds))
cicero_cds <- make_cicero_cds(input_cds, reduced_coordinates = tsne_coords)
```

but I run into the following problem:

```
Warning message in int2i(as.integer(i), n):
"NAs introduced by coercion to integer range"
Error in if (any(i < 0L)) {: missing value where TRUE/FALSE needed
Traceback:

1. reduceDimension(input_cds, max_components = 2, verbose = T, scaling = FALSE, 
 .     relative_expr = FALSE, reduction_method = "tSNE", norm_method = "none")
2. normalize_expr_data(cds, norm_method, pseudo_expr)
3. `[<-`(`*tmp*`, ncounts != 0, value = 1)
4. `[<-`(`*tmp*`, ncounts != 0, value = 1)
5. `[<-`(x, i, value = value)
6. `[<-`(x, i, value = value)
7. int2i(as.integer(i), n)
```

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Carlos, 
It seems that the error is due to the bug in Monocle2.
I think it is the same problem as this one.
https://github.com/cole-trapnell-lab/cicero-release/issues/25

As you know, we were using Cicero and Monocle2 in our tutorial, 
but we need to use Monocle3 to overcome this problem.

Thus, I made a new notebook that uses **Monocle3.**
Can you please try to analyze your data according to the new notebook?
https://morris-lab.github.io/CellOracle.documentation/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/01_atacdata_analysis_with_cicero_and_monocle3.html

**Comment by cartal** [comment]
@KenjiKamimoto-wustl122 this solved all my problems! Many thanks!
