### ISSUE TITLE
inferring cell types from markers instead of preassigned cell types

### ISSUE THREAD

**Issue by janursa** [morris-lab/CellOracle#142]
In this tutorial:
docs/notebooks/03_scRNA-seq_data_preprocessing/scanpy_preprocessing_with_Paul_etal_2015_data.ipynb

Which was very nice and informative, in the section 12.1, where you annotate clusters with the cell types, you used pre-assigned cell types from paul15. However, in section 11.1, you showed the distribution of different biomarkers. I was expecting to see that by using these biomarkers we get to see the cell type distribution, e.g. by considering the intersection of different biomarkers belonging to a specific cell type. Is there another tutorial we get to see this? 
Thanks

**Comment by aaposaav** [comment]
Fully-automated and ultra-fast cell-type identification using specific marker combinations from single-cell transcriptomic data. In this article they achieve something like that.

**Comment by janursa** [comment]
@aaposaav i didn't get your comment. Was it an answer to my previous comment? in the provided Jupyter notebook tutorial, i couldn't find where they use biomarkers to infer cell types

**Comment by KenjiKamimoto-wustl122** [comment]
@janursa 
I think aaposaav is kindly suggesting this paper for your analysis. https://www.nature.com/articles/s41467-022-28803-w

Btw, cell type inference is not the scope of celloracle and this tutorial, and actually celloracle algorithm does not require cell type assignment.  Our tutorial of scRNA-seq processing intends to show just an example for data preparation. [Please take a look at this section.](https://morris-lab.github.io/CellOracle.documentation/notebooks/03_scRNA-seq_data_preprocessing/scanpy_preprocessing_with_Paul_etal_2015_data.html#Caution)

Thus, I'm sorry but we cannot provide supports for cell type assignment request, which may requires another tool and biological background knowledge.

**Comment by janursa** [comment]
i got it now! :-) it was the name of a paper ;-) thank you both
