### ISSUE TITLE
Query: Prepare base GRN construction with ArchR

### ISSUE THREAD

**Issue by ribogod** [morris-lab/CellOracle#144]
If we are working with ArchR instead of Cicero, what are the key elements to prepare input data of base GRN construction?

**Comment by KenjiKamimoto-wustl122** [comment]
@ribogod 

Thank you for your feedback.
Unfortunately I did not make script for ArchR/SeaCell.
The key element for the input data is co-accessibility score data between scATAC-seq peaks.
Please take a look at this notebook, section #1.  https://morris-lab.github.io/CellOracle.documentation/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/02_preprocess_peak_data.html#1.-Load-scATAC-peak-data-and-peak-connection-data-made-with-Cicero

If you can prepare data in this format, you can use another package.

I am currently very busy and have not had much time to respond to requests for a CellOracle analysis.
I expect this busyness to continue for a while yet, so I can't get time to answer requests right now. However, we are planning a major update to CellOracle itself and the tutorials. We will work on this in the near future.

Kenji
