### ISSUE TITLE
About the benchmarking datasets

### ISSUE THREAD

**Issue by Chen-Li-17** [morris-lab/CellOracle#146]
Your work CellOracle published on Nature is excellent. Recently I am working on a project of GRN inference, and I wonder that will you open the source of your benchmarking dataset of 80 TFs? I believe share of this dataset will greatly contribute to the research of whole community. Thank you and looking forward to your reply!

**Comment by KenjiKamimoto-wustl122** [comment]
Let me close the issue as the data has been sent.

**Comment by Lipxiao** [comment]
> Let me close the issue as the data has been sent.

Thanks for your excellent work, And I am working on GRN inference too. Could you send me a copy of groud truth data for GRN benchmarking?

**Comment by Fucicii** [comment]
> Let me close the issue as the data has been sent.
Merry Christmas!  Could you please share the benchmarking datasets?  I would be grateful for your kind help.
