### ISSUE TITLE
tutorial for add TF infor dictionary manually

### ISSUE THREAD

**Issue by litao4tao** [morris-lab/CellOracle#15]
In current tutorial, the TF_to_TG_dictionary was inverted to TG_to_TF_dictionary, and then add to oracle object with addTFinfo_dictionary function. But it seems not right, and I don't think you need to invert TF_to_TG_dictionary.

Thanks for this wonderful tool.

**Comment by cmhct7** [comment]
Hi, thanks for your comment litao4tao! During base GRN construction, CellOracle must have access to all the TFs that can bind to a specific promoter. We designed CellOracle to look up this information using the keys from a dictionary object. So, it is best if it's in this format. For example, "Hnf4a", "Hnf4g", and "Klf4" can all bind to the "Alb" promoter, so it should be in this format: {"Alb": ["Hnf4a", "Hnf4g", "Klf4"]}. 

Thank you for trying CellOracle! Please let me know if you have any other questions!

**Comment by litao4tao** [comment]
Thanks for the explanation.
