### ISSUE TITLE
TF Binding Motif Scan not consistently working

### ISSUE THREAD

**Issue by scongrove** [morris-lab/CellOracle#156]
I am trying to run Cell Oracle using the sample data provided before using my own data. The TF binding motif scan step sometimes works, and sometimes crashes the jupyter kernel, but no changes are made to the code between the two situations. I have done all the troubleshooting suggested for the TF scan causing the kernel to crash, and since it occasionally works, I don't know what the issue could be. I can literally run the code, the kernel crashes, restart the kernel, run it again, and it works (and vice versa) so I'm very confused what is causing it to crash sometimes.

**Comment by KenjiKamimoto-wustl122** [comment]
@scongrove 

I'm guessing there is some error in gimmemotifs package in your environment. We noticed the compilation of gimmemotifs tends to have problem if you install gimmemotifs with pip. Can you please remove gimmemotifs and then reinstall it with conda?

Also, memory shortage can be a cause of issue. 
These may be useful for you to solve the issue. #74, #78, and https://morris-lab.github.io/CellOracle.documentation/installation/python_step_by_step_installation.html#install-gimmemotifs-with-conda
