### ISSUE TITLE
Plotting issues

### ISSUE THREAD

**Issue by laurabchopp** [morris-lab/CellOracle#16]
Hi Morris Lab,

Thanks for the great GRN inference package!

I've run into a small issue when trying to plot multiple plots sequentially in the same python session.
For example, if I call 

`links.plot_scores_as_rank(cluster="Bcell", n_gene=30, save=f"CellOracleFigures/Bcellranked_score")
`

It gives me a nice plot of the TF rankings for B cells.
However, if I then call

`links.plot_scores_as_rank(cluster="ImCD4", n_gene=30, save=f"ImCD4ranked_score")
`

I get a folder full of overlaid plots from both B cells and ImCD4.
The only workaround I've found is to exit python, and reload my links object. Even re-loading the links object doesn't fix it.

Second question: is there a way to set the default plot as pdf instead of png?

I'm new to Python, so perhaps these are things most people know, but I couldn't find anything on google. 

Thanks so much!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Laura,

Thank you for using celloracle!
I'm sorry but I'm currently not sure why you got overlaid plots.
I'll look into it! It may take a while. Sorry for the inconvenience.

The answer for the second question is yes. You can save your file as a pdf file.
You can change celloracle's settings by running the codes below.

`co.network_analysis.gene_analysis.settings["save_figure_as"] = "pdf"
co.network_analysis.network_structure_analysis.settings["save_figure_as"] = "pdf"
`

After running the codes, please make plots. I think your plots will be saved as pdf files.

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Laura,

I updated some plotting functions in celloracle.
Although I'm not 100% sure about the cause of thee problem, I hope this update solve your issue.

Could you please re-install celloracle and try the analysis again with new version of celloracle?  The new version is 0.3.7.

**Comment by yojetsharma** [comment]
I’m getting these folder full of plots that have a checkered background. I’m also running these on python and not Jupyter.
