### ISSUE TITLE
Error in Oracle.get_Links

### ISSUE THREAD

**Issue by debashish19211** [morris-lab/CellOracle#161]
Hi CellOracle team,

This is a query regarding the issue while running function oracle.get_links:
while using the following command:
links = oracle.get_links(cluster_name_for_GRN_unit="sub_annotation", alpha=10,n_jobs=1,verbose_level=10)

it gives the error : 
![image](https://github.com/morris-lab/CellOracle/assets/58396083/9bad5fd4-106a-40be-bebe-714b8b083cc8)
ValueError: Length of values (2) does not match length of index (13)

Can anyone suggest how can this error be resolved. Thank for your time.

**Comment by KenjiKamimoto-wustl122** [comment]
@debashish19211 
 
 I guess this is the similar issue with #37.
Can you try the solution in #37?

**Comment by debashish19211** [comment]
@KenjiKamimoto-wustl122 
Thank you for your response. The solution given in issue #37 resolved the issue.
