### ISSUE TITLE
How to check the available TF list in the oracle object

### ISSUE THREAD

**Issue by YuchenXiangEMBL** [morris-lab/CellOracle#173]
Hi,

I was running the oracle simulation and encountered the following error
`ValueError: Gene RBBP5 is not included in the base GRN; It is not TF or TF motif information is not available. Cannot perform simulation.`
I am wondering is there a method to quickly check the available TF in the GRN or base GRN in the oracle object so we can input only TFs available for simulation.

Sincerely,
Yuchen

**Comment by KenjiKamimoto-wustl122** [comment]
You can get the available TF as follows.

`oracle.active_regulatory_genes`

Or you can get more information about gene meta data by looking at anndata.var.

`oracle.adata.var`

I hope it helps.
