### ISSUE TITLE
Problems with  ma.get_tss_info function

### ISSUE THREAD

**Issue by niklasbinder** [morris-lab/CellOracle#179]
tss_annotated = ma.get_tss_info(peak_str_list=peaks, ref_genome="hg38") 

tss_annotated.tail()

NotImplementedError                       Traceback (most recent call last)
Cell In[16], line 2
      1 ##!! Please make sure to specify the correct reference genome here
----> 2 tss_annotated = ma.get_tss_info(peak_str_list=peaks, ref_genome="hg38") 
      4 # Check results
      5 tss_annotated.tail()

File ~/miniconda3/envs/celloracle/lib/python3.8/site-packages/celloracle/motif_analysis/tss_annotation.py:75, in get_tss_info(peak_str_list, ref_genome, verbose, custom_tss_file_path)
     72 queue = list_peakstr_to_df(peak_str_list)
     73 queue = BedTool.from_dataframe(queue)
---> 75 annotated = annotate_tss(tss_ref_bed=ref, queue_bed=queue, verbose=verbose)
     77 return annotated

File ~/miniconda3/envs/celloracle/lib/python3.8/site-packages/celloracle/motif_analysis/tss_annotation.py:105, in annotate_tss(tss_ref_bed, queue_bed, verbose)
    102     raise ValueError("queue bed file error")
    104 # intersect
--> 105 intersected = tss_ref_bed.intersect(queue_bed, wb=True)
    106 intersected = intersected.to_dataframe()
    108 # change name

File ~/miniconda3/envs/celloracle/lib/python3.8/site-packages/pybedtools/bedtool.py:909, in BedTool._log_to_history.<locals>.decorated(self, *args, **kwargs)
    905 def decorated(self, *args, **kwargs):
    906 
    907     # this calls the actual method in the first place; *result* is
    908     # whatever you get back
--> 909     result = method(self, *args, **kwargs)
    911     # add appropriate tags
    912     parent_tag = self._tag

File ~/miniconda3/envs/celloracle/lib/python3.8/site-packages/pybedtools/bedtool.py:244, in _wraps.<locals>.decorator.<locals>.not_implemented_func(*args, **kwargs)
    243 def not_implemented_func(*args, **kwargs):
--> 244     raise NotImplementedError(help_str)

NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

**Comment by Fucicii** [comment]
Hello, may I ask how you solved this problem, reinstall BEDtools?

**Comment by niklasbinder** [comment]
yes, it took a few attempts of reinstalling and restarting.

**Comment by Fucicii** [comment]
Thank you for your reply. I was a little unsure before, but it was solved after reinstalling.
