### ISSUE TITLE
Error with data_conversion.seurat_object_to_anndata

### ISSUE THREAD

**Issue by JunyanKan** [morris-lab/CellOracle#183]
As for the current scRNA-seq dataset, I performed former analyses in R (Seurat object). I saved the Seurat object as rds format and read it with `co.data_conversion.seurat_object_to_anndata`. However, when I checked scRNA-seq DATA with
 ```
print(f"Cell number is :{adata.shape[0]}")
print(f"Gene number is :{adata.shape[1]}")
```
 it suggested

>  ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[10], line 1
> ----> 1 print(f"Cell number is :{adata.shape[0]}")
>       2 print(f"Gene number is :{adata.shape[1]}")
> 
> AttributeError: 'dict' object has no attribute 'shape'

I have no idea how can I convert the anndata to the right format.

Here is my code:
```
# 0. Import

import os

import sys

​

import matplotlib.pyplot as plt

import numpy as np

import pandas as pd

import scanpy as sc

import anndata as ad

import seaborn as sns

ad.__version__
```

>'0.9.2'
```

import celloracle as co

co.__version__
```

> 
> /home/kjy/mambaforge/envs/celloracle_env/lib/python3.8/site-packages/loompy/bus_file.py:68: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
>   def twobit_to_dna(twobit: int, size: int) -> str:
> /home/kjy/mambaforge/envs/celloracle_env/lib/python3.8/site-packages/loompy/bus_file.py:85: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
>   def dna_to_twobit(dna: str) -> int:
> /home/kjy/mambaforge/envs/celloracle_env/lib/python3.8/site-packages/loompy/bus_file.py:102: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
>   def twobit_1hamming(twobit: int, size: int) -> List[int]:
> 
> '0.16.0'
> 
> # visualization settings
> 
> %config InlineBackend.figure_format = 'retina'
> 
> %matplotlib inline
​
```
plt.rcParams['figure.figsize'] = [6, 4.5]

plt.rcParams["savefig.dpi"] = 300
```

>#0.2. Make a folder to save graph
```
save_folder = "figures"

os.makedirs(save_folder, exist_ok=True)
```

>#1.Prepare data

># 1.0.Convert Sertat object into anndata.
```
adata = co.data_conversion.seurat_object_to_anndata("/home/kjy/Bioinfor/GRK2_HFpEF/data_sc/05Fibro_sub/Fibro_sub.rds",

                                                    delete_tmp_file=True)

adata
```

> input file name: /home/kjy/Bioinfor/GRK2_HFpEF/data_sc/05Fibro_sub/Fibro_sub.rds
> 
> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
> which was just loaded, will retire in October 2023.
> Please refer to R-spatial evolution reports for details, especially
> https://r-spatial.org/r/2023/05/15/evolution4.html.
> It may be desirable to make the sf package available;
> package maintainers should consider adding sf to Suggests:.
> The sp package is now running under evolution status 2
>      (status 2 uses the sf package in place of rgdal)
> Attaching SeuratObject
> loading seurat object ...
>   seurat object version is 4x
> Processing an assay: RNA
> 
> making AnnData ...
> 
> {'RNA': AnnData object with n_obs × n_vars = 29221 × 22523
>      obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'GEO_accession', 'sample', 'Group', 'percent_MT', 'percent_RP', 'Doublet', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'new.cluster.ids', 'RNA_snn_res.0.1', 'seurat_clusters', 'RNA_snn_res.0.2', 'RNA_snn_res.0.3', 'RNA_snn_res.0.4', 'RNA_snn_res.0.5', 'RNA_snn_res.0.6', 'RNA_snn_res.0.7', 'RNA_snn_res.0.8', 'RNA_snn_res.0.9', 'RNA_snn_res.1', 'celltype', 'active_ident'
>      var: 'variable_gene'
>      uns: 'celltype_colors', 'active_ident_colors'
>      obsm: 'X_tsne', 'X_harmony', 'X_pca', 'X_umap'
>      layers: 'raw_count'}
> 
> adata.obs
> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[13], line 1
> ----> 1 adata.obs
> 
> AttributeError: 'dict' object has no attribute 'obs'

```
print(f"Cell number is :{adata.shape[0]}")

print(f"Gene number is :{adata.shape[1]}")
```

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[10], line 1
> ----> 1 print(f"Cell number is :{adata.shape[0]}")
>       2 print(f"Gene number is :{adata.shape[1]}")
> 
> AttributeError: 'dict' object has no attribute 'shape'

**Comment by KenjiKamimoto-wustl122** [comment]
Sorry for the inconvenience, but the data conversion function is deprecated and not maintained anymore.

For a quick solution, you can solve your problem as follows.

The function seurat_object_to_anndata returns a dictionary of anndata rather than anndata object itself.
It seems your adata object is a dictionary.
Please do as follows.

```
anndata_dict = co.data_conversion.seurat_object_to_anndata("/Users/alegac/Desktop/celloralce_test/MAITS_ssTCR.sub_atac_0.9_archr_signature.rds", delete_tmp_file=True)
adata = anndata_dict["RNA"]
```
