### ISSUE TITLE
tfi.scan error: 

### ISSUE THREAD

**Issue by Edsan17** [morris-lab/CellOracle#187]
Hey there, I ran CellOracle before without any problem; however, now when I tried the tfi.scan I had the following error.

# Instantiate TFinfo object
tfi = ma.TFinfo(peak_data_frame=proc_peak, 
                ref_genome=ref_genome) 

%%time
# Scan motifs. !!CAUTION!! This step may take several hours if you have many peaks!
tfi.scan(fpr=0.02,
         motifs=None,  # If you enter None, default motifs will be loaded.
         verbose=True)

ValueError                                Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/celloracle/motif_analysis/tfinfo_core.py in scan(self, background_length, fpr, n_cpus, verbose, motifs, TF_evidence_level, TF_formatting, divide)
    397         try:
--> 398             s.set_background(genome=self.ref_genome, size=background_length) # For gimmemotifs ver 14.4
    399         except:

~/.local/lib/python3.7/site-packages/gimmemotifs/scanner.py in set_background(self, fname, genome, size, nseq, gc, gc_bins)
    752                     fa = RandomGenomicFasta(genome, size, nseq)
--> 753                 cache.set(self.background_hash, (fa, gc_bins))
    754         lock.release()

/opt/conda/envs/celloracle/lib/python3.7/site-packages/diskcache/core.py in set(self, key, value, expire, read, tag, retry)
    771         expire_time = None if expire is None else now + expire
--> 772         size, mode, filename, db_value = self._disk.store(value, read, key=key)
    773         columns = (expire_time, tag, size, mode, filename, db_value)

/opt/conda/envs/celloracle/lib/python3.7/site-packages/diskcache/core.py in store(self, value, read, key)
    220         else:
--> 221             result = pickle.dumps(value, protocol=self.pickle_protocol)
    222 

ValueError: pickle protocol must be <= 4

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

~/.local/lib/python3.7/site-packages/celloracle/motif_analysis/tfinfo_core.py in scan(self, background_length, fpr, n_cpus, verbose, motifs, TF_evidence_level, TF_formatting, divide)
    398             s.set_background(genome=self.ref_genome, size=background_length) # For gimmemotifs ver 14.4
    399         except:
--> 400             s.set_background(genome=self.ref_genome, length=background_length)# For old gimmemotifs ver 13
    401 
    402         #s.set_background(genome="mm9", length=400)

TypeError: set_background() got an unexpected keyword argument 'length'

I have cell oracle co.__version__  '0.13.1' and downgraded GimmeMotifs from v 0.17.0 to version: 0.14.4 (neither of them are working).

Also, my processed peaks look fine:
proc_peak = check_peak_format(proc_peak, ref_genome)
Peaks before filtering:  32860
Peaks with invalid chr_name:  0
Peaks with invalid length:  0
Peaks after filtering:  32860

Could you help me with this, please?

**Comment by KenjiKamimoto-wustl122** [comment]
I think the issue is caused by an installation problem in gimmemotifs. 
Can you try to uninstall gimmemotifs and re-install using conda? 
Please try `conda install gimmemotifs` and don't try `pip install gimmemotifs`.

**Comment by Edsan17** [comment]
Oh, thank you! It works now! I was trying pip install and it was the problem, apparently. Thank you so much!

**Comment by KenjiKamimoto-wustl122** [comment]
Great! I'm glad it works!
