### ISSUE TITLE
Saving plots as individual files?

### ISSUE THREAD

**Issue by njrobins** [morris-lab/CellOracle#203]
Hello!

Thanks so much for creating and maintaining this great tool. Based on the tutorial, it seems the pipeline is designed to be run in Jupyter; however, my institution is currently having some technical issues with Jupyter, so I have tried running it in a Python interactive session on our HPC (i.e., through the command line). Everything seems to run well, except, of course, I am unable to see charts/plots in-line as I would in a Jupyter notebook. Since the plot-generating functions all appear to be built into CellOracle, I am not sure that simply following a plot-generating step with `plt.savefig('FILENAME')` will be sufficient to create separate files containing each plot (in fact, I have tried this, and so far it has yielded only blank png/pdf files). Is there a way that users can direct CellOracle to save plots as individual files, as opposed (or in addition) to viewing them in-line? I know this is possible with some functions, but not universally so. I should also note that I have only run the pseudotime calculation thus far.

Thank you again! I am happy to provide code or any additional information that would be helpful.

**Comment by yojetsharma** [comment]
How did you solve this? It would be great if you could share the solution!

**Comment by njrobins** [comment]
Unfortunately, I did not find a solution per se. I ended up running my workflow in a Jupyter notebook and was able to save plots directly from the UI as they were generated. However, all of these were PNGs, and I never did find a way to change the file extension (there is probably a way through matplotlib, but I did not troubleshoot comprehensively). I hope this helps!
