### ISSUE TITLE
Error in calculating embedding shift

### ISSUE THREAD

**Issue by Larrycpan** [morris-lab/CellOracle#206]
Thanks for the great tool. I was encountering the error `'AttributeError: 'csr_matrix' object has no attribute 'A'` when using the function `calculate_embedding_shift`. Do you know how to resolve? Look forward to your reply.
![QQ截图20240711135941](https://github.com/morris-lab/CellOracle/assets/65411328/920dcbf3-66da-411b-abe1-02ab5d4fea3f)

**Comment by hzuzu** [comment]
Hi,
I am having the same issues. while working through the tutorial of [1. In silico gene perturbation with GRNs](https://morris-lab.github.io/CellOracle.documentation/notebooks/05_simulation/Gata1_KO_simulation_with_Paul_etal_2015_data.html).
I am using cellOracle version '0.18.0'
The calculate embedding step fails:

```{python}
# Calculate embedding
oracle.calculate_embedding_shift(sigma_corr=0.05)
```

<img width="1450" alt="Screenshot 2024-07-15 at 12 54 10 PM" src="https://github.com/user-attachments/assets/3d848186-cb9e-49ee-a910-2b55b25ca70d">

The csr_matrix object does not seem to have any '.A' attribute.

**Comment by Larrycpan** [comment]
I found the error is raised from the version of `scipy`. Install the older `scipy` library (`pip install scipy==1.12.0`) would resolve problem.

**Comment by hzuzu** [comment]
That worked.
Thanks @Larrycpan !
