### ISSUE TITLE
Add saccharomyces cerevisiae R64-1-1 reference genome

### ISSUE THREAD

**Issue by cskokgibbs** [morris-lab/CellOracle#23]
Hi,

I am interested in using cell-oracle's motif scan on the saccharomyces cerevisiae R64-1-1 reference genome. I was wondering if this could be added to the tss_ref_data? thanks in advance!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Claudia,

We added tss reference data for "sacCer2" and "sacCer3" S.Cerevisiae reference genome to celloracle's tss reference data. 
Please re-install celloracle to use latest version of celloracle (version 0.4.1).

We are using homer's database to construct our tss reference data, and homer supports only two reference genomes above for S.Cerevisiae. http://homer.ucsd.edu/homer/
I hope it works for your saccharomyces cerevisiae dataset. 

Besides, although we added tss dataset for S.Cerevisiae, we have not tested celloracle with S.Cerevisiae data.
Please tell us if you find some issue with it.

**Comment by cskokgibbs** [comment]
Hi Kenji,

Thanks so much for adding this. I was wondering how this file was generated: sacCer3_tss_info.bed. Specifically, what the start, stop locations correspond to in the genome as well as the scores associated? Besides this the S.Cervevisiae data works just fine in cell oracle. Thanks in advance!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Claudia,

(1) The start and stop location in the bed file correspond to the information of "promoter-TSS" site in Homer's database. 
(2) The 5th column in the bed file is not score, but it is the distance to TSS. Although we are storing this information, this information is not used for the analysis now.

To make this bed file, I downloaded annotation data from Homer web site, then extracted information for promoter and tss locations.
Please look at the following script for more detailed information.
 
Here is the python script I used. 
https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/misc/make_tss_referenece_from_homer_data-S%20cerevisiae.ipynb

Thank you for the question and coments! 
We have not tried celloracle with S.Cerevisiae data and Your feedback helps us a lot!

**Comment by cskokgibbs** [comment]
Hi Kenji,

I originally noticed that the switch statement in _get_dic_motif2TF places S.cerevisiae in the same category as human motifs. As a result I was generating a connectivity matrix with S.cerevisiae genes and human TFs. I've spent a considerable amount of time creating the necessary motif2factors file and trying to implement it within the cell oracle code base, but am running into issues i'm not certain how to solve. I was wondering if you might have any suggestions on how I could get the correct S.cerevisiae motif names into the connectivity matrix. Your feedback is greatly appreciated!

Best,
Claudia

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Claudia,

We made major update in celloracle. Please re-install celloracle.
Also, we updated celloracle tutorial notebook.
https://morris-lab.github.io/CellOracle.documentation/notebooks/02_motif_scan/02_atac_peaks_to_TFinfo_with_celloracle_20200801.html

With the new version (celloracle>=0.5.0), you can select TF motif database. 

In the new version, we changed the dafalut motif database for S.cerevisiae.
If you set S.cerevisiae data, CisDB S.cerevisiae motifs, "CisDB_ver2_Saccharomyces_cerevisiae.pfm", will be loaded. 
This motif does not includes human motifs.

Also, you have another option: you can use the motif dataset for fungi in JASPAR: "JASPAR2020_fungi.pfm"

Please try new version of celloracle with new celloracle tutorials. I hope it solve your issue.
