### ISSUE TITLE
alternative method for motif scan

### ISSUE THREAD

**Issue by wangmhan** [morris-lab/CellOracle#25]
Hi,

I wonder if it is possible to import results of motif scan from other methods, such as Homer.
As I really struggled hard with gimmemotifs, and always end up with error. No matter if it is the specific version mentioned in the installation, or their latest version. I went quite smooth with Homer.

I think it would make CellOracle more flexible.

Thanks & best regards,
Menghan

**Comment by KenjiKamimoto-wustl122** [comment]
Thank you for the suggestion.
Having multiple options for motif scanning would be great!

Although we cannot do it immediately due to the time constraint, we will try it in the future release.

If you don't mind, could you please send us your error message or any information about the error?

Thanks,

**Comment by wangmhan** [comment]
Yes, sure.

As I still get stuck in CellOracle as no reference genome for chicken. I run gimmemotifs directly just to give it a try.
[slurm-13091988.out.txt](https://github.com/morris-lab/CellOracle/files/4897662/slurm-13091988.out.txt)


My steps:
genomepy install ftp://ftp.ensembl.org/pub/release-97/fasta/gallus_gallus/dna/Gallus_gallus.GRCg6a.dna_sm.toplevel.fa.gz url --localname gg6_ensembl97
ln -s ~/references/ens_g6_atac/Gg6_extended_200819.filter.gtf
gimme motifs -N 8 -p JASPAR2020_vertebrates -g gg6_ensembl97 in.bed out_dir

I attached the error log.

Installation information (please complete the following information):

OS: CentOS 7.8
Installation: conda install gimmemotifs
Version 0.14.4
genomepy --version 0.8.3 

[slurm-13091988.out.txt](https://github.com/morris-lab/CellOracle/files/4897666/slurm-13091988.out.txt)

**Comment by KenjiKamimoto-wustl122** [comment]
Thank you very much Menghan!

I'll look into it!

Kenji
