### ISSUE TITLE
run scan motifs independently, then import into cellOracle

### ISSUE THREAD

**Issue by wangmhan** [morris-lab/CellOracle#26]
Hi,

I wonder if it is possible to run gimme motifs or scan independently, then import the results to cellOracle for the following steps.
I am asking this, as the version of gimme CellOracle needed did not work well in my system. While the latest version of gimmemotifs and genomepy work well. It would be great if there is a port for that.

Big thanks!

**Comment by wangmhan** [comment]
Hi,

I found the reason of the difference between my gimme output and the output from tutorial is mainly because I run the gimme scan with command line, while the tutorial is actually using gimme python API. I will try to run with gimme python API.

By the way, I think it would be helpful if can give an example folder, with all the results from each step. So people who would like to use this package can easily check if the format and other stuffs are same or not.

**Comment by sam-morris** [comment]
Hi wangmhan. Yes, we do recommend you follow the tutorial. Please remember that this work is currently unpublished - other features you suggest, such as an example folder, will come in time. Sam.

**Comment by wangmhan** [comment]
Hi Sam,

I also would like to follow the tutorial. The problem is the version of
genomepy didn't work in the server I used...
