### ISSUE TITLE
Need to pre-process anndata after converting from Seurat object? 

### ISSUE THREAD

**Issue by laijen000** [morris-lab/CellOracle#29]
Hi! I used the celloracle command line API to convert my processed seurat object to anndata. Next, do I need to pre-process the anndata (as in Step 3A of the tutorial) too? 

Thank you,
Jenny

**Comment by laijen000** [comment]
Hello! Thank you again for this cool tool! I have a related question to using already processed Seurat objects. After using the command line API "seuratToAnndata", I ran into an issue with oracle.perform_PCA() taking a very long time and the process getting killed. From #17 , I learned that I need to filter the anndata to get just the variable genes. So I went through the scanpy preprocessing tutorial and ran: 

`sc.pp.filter_genes(adata, min_counts=1)
# Normalize gene expression matrix with total UMI count per cell
sc.pp.normalize_per_cell(adata, key_n_counts='n_counts_all')
# Select top 3000 highly-variable genes
filter_result = sc.pp.filter_genes_dispersion(adata.X,
                                              flavor='cell_ranger',
                                              n_top_genes=3000,
                                              log=False)
# Subset the genes
adata = adata[:, filter_result.gene_subset]
# Renormalize after filtering
sc.pp.normalize_per_cell(adata)
# keep raw cont data before log transformation
adata.raw = adata
# Log transformation and scaling
sc.pp.log1p(adata)
sc.pp.scale(adata)
# PCA
sc.tl.pca(adata, svd_solver='arpack')
# Diffusion map
sc.pp.neighbors(adata, n_neighbors=4, n_pcs=20)
sc.tl.diffmap(adata)
# Calculate neighbors again based on diffusionmap
sc.pp.neighbors(adata, n_neighbors=10, use_rep='X_diffmap')
sc.tl.louvain(adata, resolution=0.8)

# save the anndata 
adata.write_h5ad("processedanndata.h5ad")`

Now, when I try to instantiate the oracle object, I run into an issue KeyError: 'Cluster_colors'. 
```
# use raw mRNA count as input to oracle
adata.X = adata.raw.X.copy()
# instantiate oracle object 
oracle.import_anndata_as_raw_count(adata=adata, cluster_column_name= "Cluster", embedding_name="X_umap")
```
I want to use my seurat cluster annotations "Cluster", which are the cell type identities, for cluster_column_name (instead of lovain_annot as in the tutorial). However this seems to be part of the problem. If I set cluster_column_name = "seurat_clusters", I do not get an error at this step, and the seurat_clusters are simply numbers. 

Thank you again for your help!

**Comment by KenjiKamimoto-wustl122** [comment]
HI Jenny,

You don't need to re-do preprocessing if you have a scRNA-seq data generated with Seurat.

I made a new notebook for you. Please use it. https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/04_Network_analysis/Network_analysis_with_Seurat_data.ipynb

And, the error you got means that your scRNA-seq data does not includes the color information for your clusters.
Although I don't know why color information does not exist in your data, you can fix this problem by generating new color information.
You can generate color information by making a plot using scanpy: scanpy generate color information when you first visualizing your data.
In your case, please try the code below and then do celloracle analysis. 
`sc.pl.umap(adata, color="Cluster")`

**Comment by laijen000** [comment]
I see, thank you so much!
