### ISSUE TITLE
error when importing cell oracle

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [morris-lab/CellOracle#32]
Hi!

I installed cell oracle, as well as the other packages. however, when importing cell oracle, I get the following error:

Error: use() got an unexpected keyword argument 'warn'
>>> import celloracle as co
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/celloracle/__init__.py", line 8, in <module>
    from . import utility, network, network_analysis, go_analysis, data, data_conversion, oracle_utility
  File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/celloracle/utility/__init__.py", line 18, in <module>
    from .load_hdf5 import load_hdf5
  File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/celloracle/utility/load_hdf5.py", line 8, in <module>
    from ..motif_analysis.tfinfo_core import load_TFinfo
  File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/celloracle/motif_analysis/__init__.py", line 11, in <module>
    from .motif_analysis_utility import is_genome_installed
  File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/celloracle/motif_analysis/motif_analysis_utility.py", line 24, in <module>
    from gimmemotifs.scanner import Scanner
  File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/gimmemotifs/scanner.py", line 29, in <module>
    from gimmemotifs.utils import parse_cutoff,as_fasta,file_checksum
  File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/gimmemotifs/utils.py", line 29, in <module>
    from gimmemotifs.plot import plot_histogram
  File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/gimmemotifs/plot.py", line 19, in <module>
    mpl.use("Agg", warn=False)
TypeError: use() got an unexpected keyword argument 'warn'

Thanks!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi,

It seems that the error is in the gimmemotifs package.
We confirmed that gimmemotifs version 0.14.4 works well.

Could you please try this command to install gimmemotifs version 0.14.4 in your environment?

`pip install gimmemotifs==0.14.4 genomepy==0.8.4`

**Comment by bio-ruxandra-tesloianu** [comment]
many thanks!

I installed this, seems like the right version was already installed in celloracle_env

I then opened python to import cell oracle and the same error as before appeared. 

command:
(celloracle_env)jovyan@jupyter-bio-2druxandra-2dtesloianu:~$ pip install gimmemotifs==0.14.4 genomepy==0.8.4
Requirement already satisfied: gimmemotifs==0.14.4 in ./my-conda-envs/celloracle_env/lib/python3.6/site-packages (0.14.4)

**Comment by KenjiKamimoto-wustl122** [comment]
Thank you for trying. 

I'm still suspecting something wrong with gimmemotifs because of your error message below. It came from gimmemotifs.

File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/**gimmemotifs**/plot.py", line 19, in 
mpl.use("Agg", warn=False)
TypeError: use() got an unexpected keyword argument 'warn'


I need to clarify where the problem is occurring.
Could you please try to load gimmemotifs only in the python; (please do not imort celloracle now)?

`import gimmemotifs`

I expect you will get the same error. If so, the problem is in the gimmemotifs.
In that case, I recommend uninstalling gimmemotifs and then please install gimmemotifs again.


If you get no error when you import gimmemotifs, the problem is something else.

**Comment by bio-ruxandra-tesloianu** [comment]
hi, thanks a lot!


This is what happens when I import gimmemotifs. as you can see, it works fine.
(celloracle_env)jovyan@jupyter-bio-2druxandra-2dtesloianu:$ python
Python 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gimmemotifs
>>> import gimmemotifs as gm
>>>

**Comment by bio-ruxandra-tesloianu** [comment]
> Thank you for trying.
> 
> I'm still suspecting something wrong with gimmemotifs because of your error message below. It came from gimmemotifs.
> 
> File "/home/jovyan/my-conda-envs/celloracle_env/lib/python3.6/site-packages/**gimmemotifs**/plot.py", line 19, in
> mpl.use("Agg", warn=False)
> TypeError: use() got an unexpected keyword argument 'warn'
> 
> I need to clarify where the problem is occurring.
> Could you please try to load gimmemotifs only in the python; (please do not imort celloracle now)?
> 
> `import gimmemotifs`
> 
> I expect you will get the same error. If so, the problem is in the gimmemotifs.
> In that case, I recommend uninstalling gimmemotifs and then please install gimmemotifs again.
> 
> If you get no error when you import gimmemotifs, the problem is something else.

**Comment by bio-ruxandra-tesloianu** [comment]
hi! I uninstalled gimmemotifs anyway and installed back again and it now works! I am not sure what the reason for it not wiring was, but thanks a lot
