### ISSUE TITLE
motif_analysis.scan runtime crash: Segmentation fault: 11

### ISSUE THREAD

**Issue by gav-sturm** [morris-lab/CellOracle#33]
While running tfi.scan I am running into the following error which seems to be related to (https://kb.iu.edu/d/aqsj). Any ideas what could be causing this? I am using human, hg38, reference genome and using 14000 peaks from ATACseq data. I have run it with the default motifs and the program still crashes.

Here is the output:
Checking your motifs... Motifs format looks good. 

Initiating scanner... 

Calculating FPR-based threshold. This step may take substantial time when you load a new ref-genome. It will be done quicker on the second time. 

Convert peak info into DNA sequences ... 

Scanning motifs ... It may take several hours if you proccess many peaks. 

HBox(children=(HTML(value=''), FloatProgress(value=1.0, bar_style='info', layout=Layout(width='20px'), max=1.0), HTML(value='')))
Segmentation fault: 11

**Comment by KenjiKamimoto-wustl122** [comment]
HI gav-strum,

It seems that gimmemotifs crushed during the scanning process. gimmemotifs is one of the python package used in the celloracle.
As you suspected, I think "Segmentation fault: 11" is a basic memory error.
However I cannot identify the cause of this problem. 
The possible reasons are below.

- memory shortage
- gimmemotifs compile error
- os environment error

If possible, can you please try to use celloracle in a different PC? I guess a computer with larger memory will help.
