### ISSUE TITLE
question: Seurat label transfer

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [morris-lab/CellOracle#34]
Hi,

I have already processed my scRNAseq and scATACseq data using Seurat and transferred labels from ScRNAseq to my scATACseq. at the moment I am in the process of running celloracle using peaks From all cells in the same experiment. I was wondering if it would make sense to separate peaks based on annotated cluster and then calculate everything (Cicero, TF scan) on a per cluster basis. I am asking this because this would limit the number of potential regulatory TFs to those relevant to each cluster.

Best wishes,
Ruxandra

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Ruxandra,

Currently, celloracle just support a single peak file for base-GRN construction, 
and it does not support the separate peaks for the cluster. 
However, we think it is a good idea! 
We are planning to implement such a feature in a future release.
I will message you when we implement such functions.
