### ISSUE TITLE
Apply a new order to plot_network_entropy_distributions

### ISSUE THREAD

**Issue by sa95078** [morris-lab/CellOracle#43]
Is there a way to reorder clusters in plot_network_entropy_distributions function? Thank you!

**Comment by KenjiKamimoto-wustl122** [comment]
Yes. We can change cluster order by the following steps.

1) Let's assume we have GRN like below.  If you plot network_entropy, you will get this plot. 
<img width="564" alt="スクリーンショット 2021-01-30 15 55 05" src="https://user-images.githubusercontent.com/42547768/106368994-8ad9f380-6313-11eb-9715-c1f56e6598c9.png">

2) Current order is stored in the attribute of "palette"
<img width="349" alt="スクリーンショット 2021-01-30 15 39 19" src="https://user-images.githubusercontent.com/42547768/106368823-4dc13180-6312-11eb-8946-5b1af7d90b60.png">

So you can get list of cluster like below.
<img width="799" alt="スクリーンショット 2021-01-30 15 47 02" src="https://user-images.githubusercontent.com/42547768/106368842-73e6d180-6312-11eb-81e0-d30770d69a07.png">

3) Please make a new list. 
<img width="978" alt="スクリーンショット 2021-01-30 15 49 48" src="https://user-images.githubusercontent.com/42547768/106368893-d8a22c00-6312-11eb-83df-970ceefad681.png">

4) Update palette using your new list. 
`links.palette = links.palette.loc[new_order]`
<img width="485" alt="スクリーンショット 2021-01-30 15 40 00" src="https://user-images.githubusercontent.com/42547768/106368946-2880f300-6313-11eb-8e36-69bb604d525a.png">

5) You will get a new plot with new order.
<img width="562" alt="スクリーンショット 2021-01-30 15 40 11" src="https://user-images.githubusercontent.com/42547768/106368957-39c9ff80-6313-11eb-9614-69d0f110318c.png">



Kenji

**Comment by sa95078** [comment]
Thank you!
