### ISSUE TITLE
Add to library path

### ISSUE THREAD

**Issue by f6v** [morris-lab/CellOracle#44]
I'm trying to run `CellOracle` in an HPC environment. Naturally, there's an issue with installing the dependencies. Some of the R packages aren't there, and the backlog for centralised installation is quite big.

I figured out I could create a new key in config: https://github.com/morris-lab/CellOracle/blob/6b4f9437ffa2071e4e32ff65d736c6c94223e527/celloracle/network_analysis/use_r_scripts.py#L31

something like:
```
config = {"R_path": "R", "lib_path": None, "n_cpu": cpu_count()}
```
I could then set it to point to my own library path where I have the packages. This config could then be provided as an argument to the `Rscript`: 
https://github.com/morris-lab/CellOracle/blob/6b4f9437ffa2071e4e32ff65d736c6c94223e527/celloracle/network_analysis/use_r_scripts.py#L100

Then the R code can use it append to the `.libPaths`.

So I've got two questions:
- Does that sound reasonable?
- Would you potentially accept that into the code base as a PR?

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Igor,

It sounds great! Thank you for the suggestion! 
I will update our codes according to your advice.
