### ISSUE TITLE
The embedding param when importing data for network analysis

### ISSUE THREAD

**Issue by f6v** [morris-lab/CellOracle#45]
I'm following the tutorial and want to apply `CellOracle` to my own data. I'm not sure about the `embedding_name` param: https://github.com/morris-lab/CellOracle/blob/63860681467ee573237f73a634d9af45a33fc2c6/celloracle/trajectory/oracle_core.py#L298

What kind of _embedding_ can that be? I have a mixture of 3 cancer cell lines in one dataset, so I guess a trajectory isn't a good fit here. Can I use something like PCA or UMAP?

Thanks in advance!

**Comment by KenjiKamimoto-wustl122** [comment]
Hi f6v,

For the "embedding", please enter the name of dimensional reduction data. 
Details and example are described here.
https://morris-lab.github.io/CellOracle.documentation/notebooks/04_Network_analysis/Network_analysis_with_Paul_etal_2015_data.html#2.1.-load-gene-expression-data-into-oracle-object.
