### ISSUE TITLE
Error when importing AnnData

### ISSUE THREAD

**Issue by f6v** [morris-lab/CellOracle#46]
I get the error when importing `AnnData` object:
```
import_anndata_as_raw_count(adata=adata, cluster_column_name="cell_type", embedding_name="X_pca")
```
The error is originates from `_get_clustercolor_from_anndata`, as there's no `cell_type_colors` in my data:
```
KeyError: 'cell_type_colors'
```
 I use pre-defined cell types and not the clustering results, that's why there's no color information. I guess I'd have to populate that manually with some random colors?

**Comment by KenjiKamimoto-wustl122** [comment]
Hi f6v,

This error means celloracle could not find the color information for "cell_type".
Please run this command below before importing addata.

`sc.pl.pca(adata, color="cell_type")`

If you make plot with scanpy's plotting function, it will generate cluster color data automatically.
And after running this code, please try to import your anndata.

**Comment by f6v** [comment]
Thanks! I wasn't aware of that.
