### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by smorabit** [morris-lab/CellOracle#47]
Hi,

I have been trying to install CellOracle using the instructions [here](https://morris-lab.github.io/CellOracle.documentation/installation/index.html). All of the dependencies installed without a problem, but when I tried to run `pip install git+https://github.com/morris-lab/CellOracle.git`, I got an error message that I do not know how to resolve:

```
$pip install git+https://github.com/morris-lab/CellOracle.git
Collecting git+https://github.com/morris-lab/CellOracle.git
  Cloning https://github.com/morris-lab/CellOracle.git to /tmp/pip-req-build-drlsr_n9
  Running command git clone -q https://github.com/morris-lab/CellOracle.git /tmp/pip-req-build-drlsr_n9
    ERROR: Command errored out with exit status 1:
     command: /data/homezvol1/smorabit/.conda/envs/celloracle_env/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-drlsr_n9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-drlsr_n9/setup.py'"'"';
f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-19oh25yb
         cwd: /tmp/pip-req-build-drlsr_n9/
    Complete output (21 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-drlsr_n9/setup.py", line 16, in <module>
        from celloracle import __version__
      File "/tmp/pip-req-build-drlsr_n9/celloracle/__init__.py", line 8, in <module>
        from . import utility, network, network_analysis, go_analysis, data, data_conversion, oracle_utility

      File "/tmp/pip-req-build-drlsr_n9/celloracle/utility/__init__.py", line 18, in <module>
        from .load_hdf5 import load_hdf5
      File "/tmp/pip-req-build-drlsr_n9/celloracle/utility/load_hdf5.py", line 8, in <module>
        from ..motif_analysis.tfinfo_core import load_TFinfo
      File "/tmp/pip-req-build-drlsr_n9/celloracle/motif_analysis/__init__.py", line 11, in <module>
        from .motif_analysis_utility import is_genome_installed
      File "/tmp/pip-req-build-drlsr_n9/celloracle/motif_analysis/motif_analysis_utility.py", line 24, in <module>
        from gimmemotifs.scanner import Scanner
      File "/data/homezvol1/smorabit/.conda/envs/celloracle_env/lib/python3.6/site-packages/gimmemotifs/scanner.py", line 29, in <module>
        from gimmemotifs.utils import parse_cutoff,as_fasta,file_checksum
      File "/data/homezvol1/smorabit/.conda/envs/celloracle_env/lib/python3.6/site-packages/gimmemotifs/utils.py", line 29, in <module>
        from gimmemotifs.plot import plot_histogram
      File "/data/homezvol1/smorabit/.conda/envs/celloracle_env/lib/python3.6/site-packages/gimmemotifs/plot.py", line 19, in <module>
        mpl.use("Agg", warn=False)
    TypeError: use() got an unexpected keyword argument 'warn'
    ----------------------------------------
WARNING: Discarding git+https://github.com/morris-lab/CellOracle.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I would greatly appreciate your help in resolving this as I was really interested to use CellOracle!

Thanks,
Sam

**Comment by KenjiKamimoto-wustl122** [comment]
Hi, Thank you for your feedback!

I guess the error was caused by "gimmemotifs", that is one of the packages used in celloracle
because the situation looks similar to this https://github.com/morris-lab/CellOracle/issues/32

Can you please remove gimmemotifs and try to install it again as follows?
`
pip uninstall gimmemotifs
`
and then
`
conda install gimmemotifs==0.14.4 genomepy==0.8.4
`

Kenji

**Comment by smorabit** [comment]
Thanks for the help, I was able to install celloracle by installing those versions of gimmemotifs and genomepy. However, initially I did get another installation error which was resolved using this:

`conda install ipyvuetify`

**Comment by rlittman16** [comment]
I am having issues with the r version that's compatible with these packages. If I let conda choose default after installing celloracle, but before the r packages it chooses 3.2.1, which isn't compatible with later R packages needed. I tried 3.6.1, but am having compatibility issues now when trying "install other python libraries" 
`conda install goatools pyarrow tqdm joblib jupyter gimmemotifs==0.14.4 genomepy==0.8.4`

**Comment by KenjiKamimoto-wustl122** [comment]
Hi rittman16,

Thank you for your feedback.
Could you please post the error messages you got? I need more information to figure out what is going on.
Also, could you please tell me information about your environment, such as OS, and other python packages installed in your environment? Please tell me the output of  `conda list` command.

In my understanding, most of the Python packages used by celloracle do not depend on R, so it seems that the cause of the error is something other than the R version.  R 3.6 works in my PC.

Also, please let me ask one more question.
Are you installing celloracle in a new conda environment? I recommend making a new conda environment for celloracle and start with it to avoid compatibility error.

**Comment by rlittman16** [comment]
Hello,

I am following the steps here: https://github.com/morris-lab/CellOracle under the pdf documentation link. 

Yes I'm using a new conda environment.

Once I get to 1.1.4 in the documentation I need to install R>=3.5, but conda can't find an R version that satisfies that requirement. It tries to install R 3.2.1 by default. If I try R>=3.5 it says:

`Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.`


Here are the results for conda list:
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
abseil-cpp                20200923.3           h9c3ff4c_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
anndata                   0.7.5            py36h5fab9bb_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               20.1.0           py36h8f6f2f9_2    conda-forge
arpack                    3.7.0                hdefa2d7_2    conda-forge
arrow-cpp                 3.0.0           py36h3d3e26e_10_cpu    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
aws-c-cal                 0.4.5                h76129ab_8    conda-forge
aws-c-common              0.5.2                h7f98852_0    conda-forge
aws-c-event-stream        0.2.7                h6bac3ce_1    conda-forge
aws-c-io                  0.9.1                ha5b09cb_1    conda-forge
aws-checksums             0.1.11               h99e32c3_3    conda-forge
aws-sdk-cpp               1.8.151              hceb1b1e_1    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.3              pyhd8ed1ab_0    conda-forge
bedtools                  2.30.0               h7d7f7ad_1    bioconda
biopython                 1.78             py36h8f6f2f9_2    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
boltons                   20.2.1             pyh9f0ad1d_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py36h8f6f2f9_1001    conda-forge
bucketcache               0.12.1           py36h9f0ad1d_2    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
celloracle                0.6.5                    pypi_0    pypi
certifi                   2020.12.5        py36h5fab9bb_1    conda-forge
cffi                      1.14.4           py36h211aa47_0    conda-forge
chardet                   4.0.0            py36h5fab9bb_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
configparser              5.0.2              pyhd8ed1ab_0    conda-forge
cryptography              3.4.7            py36hb60f036_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.22          py36hc4f0c31_0    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 5.0.3              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dinamo                    1.0                  h78a066a_0    bioconda
diskcache                 5.2.1              pyh44b312d_0    conda-forge
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.16             py36h5fab9bb_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.10               h9c3ff4c_0    conda-forge
fa2                       0.3.5                    pypi_0    pypi
feather-format            0.4.1              pyh9f0ad1d_0    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
future                    0.18.2           py36h5fab9bb_3    conda-forge
gadem                     1.3.1                h779adbc_3    bioconda
genomepy                  0.8.4                      py_0    bioconda
get_version               2.1                        py_1    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
ghostscript               9.53.3               h58526e2_2    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
gimmemotifs               0.14.4           py36h4c5857e_2    bioconda
glib                      2.66.3               h58526e2_0    conda-forge
glog                      0.4.0                h49b9bf7_3    conda-forge
glpk                      4.65              h9202a9a_1004    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
goatools                  1.0.15             pyh3252c3a_0    bioconda
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.42.3               h0511662_0    conda-forge
grpc-cpp                  1.36.4               hf89561c_1    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
h5py                      3.1.0           nompi_py36hc1bc4f5_100    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
homer                     4.11            pl5262h7d875b9_4    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.10.0           py36h5fab9bb_0    conda-forge
importlib_metadata        3.10.0               hd8ed1ab_0    conda-forge
ipykernel                 5.5.3            py36hcb3619a_0    conda-forge
ipython                   7.16.1           py36he448a4c_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipyvue                    1.5.0              pyhd3deb0d_0    conda-forge
ipyvuetify                1.6.2              pyh44b312d_0    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.17.2           py36h5fab9bb_1    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0            py36h5fab9bb_6    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py36h5fab9bb_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kiwisolver                1.3.1            py36h605e78d_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
legacy-api-wrap           1.2                        py_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.76.0               hc4aaa36_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.0                h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libllvm11                 11.1.0               hf817b99_1    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.15.6               h780b84a_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libthrift                 0.14.1               he6d91bd_1    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libtool                   2.4.6             h58526e2_1007    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxgboost                1.3.3                h9c3ff4c_2    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
llvm                      11.1.0               h32600fe_1    conda-forge
llvmlite                  0.36.0           py36h05121d2_0    conda-forge
logbook                   1.5.3            py36h8f6f2f9_4    conda-forge
logomaker                 0.8                pyh864c0ab_1    bioconda
loompy                    3.0.6                    pypi_0    pypi
louvain                   0.7.0            py36hf105032_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                1.1.1            py36h8f6f2f9_3    conda-forge
matplotlib                3.2.2                         1    conda-forge
matplotlib-base           3.2.2            py36hb8e4980_0    conda-forge
meme                      5.3.0           py36pl526h31c59b1_0    bioconda
metis                     5.1.0             h58526e2_1006    conda-forge
mistune                   0.8.4           py36h8f6f2f9_1003    conda-forge
mock                      4.0.3            py36h5fab9bb_1    conda-forge
mpi                       1.0                     openmpi    conda-forge
mysql-connector-c         6.1.11            h6eb9d5d_1007    conda-forge
natsort                   7.1.1              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py36h5fab9bb_3    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.5                        py_0    conda-forge
norns                     0.1.5              pyh864c0ab_1    bioconda
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.3.0            py36h5fab9bb_0    conda-forge
numba                     0.53.1           py36h0c5f33e_0    conda-forge
numexpr                   2.7.3            py36h284efc9_0    conda-forge
numpy                     1.19.5           py36h2aa4a07_1    conda-forge
numpy-groupies            0.9.13                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openmpi                   4.0.5                h9b22176_4    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
orc                       1.6.7                heec2584_1    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.1.5                    pypi_0    pypi
pandoc                    2.12                 h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pathlib                   1.0.1            py36h5fab9bb_4    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-algorithm-cluster    1.58            pl526h14c3975_0    bioconda
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.44            pl526h14c3975_1    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-dbi                  1.642                   pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-file-which           1.23                    pl526_0    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-template        2.97                    pl526_1    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-log-log4perl         1.49                    pl526_0    bioconda
perl-math-cdf             0.1             pl526h14c3975_5    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.2            py36ha6010c0_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prometheus_client         0.10.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
prompt_toolkit            3.0.18               hd8ed1ab_0    conda-forge
prosampler                1.0                  hc9558a2_0    bioconda
psutil                    5.8.0            py36h8f6f2f9_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-xgboost                1.3.3            py36h5fab9bb_2    conda-forge
pyarrow                   3.0.0           py36h6200943_10_cpu    conda-forge
pybedtools                0.8.2            py36hb377018_1    bioconda
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydot                     1.4.2            py36h5fab9bb_0    conda-forge
pyfaidx                   0.5.9.5            pyh3252c3a_0    bioconda
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pygraphviz                1.6              py36he9cec78_1    conda-forge
pynndescent               0.5.2              pyh44b312d_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py36hcca6a23_4    conda-forge
pyrsistent                0.17.3           py36h8f6f2f9_2    conda-forge
pysam                     0.16.0.1         py36h61e5637_3    bioconda
pysocks                   1.7.1            py36h5fab9bb_3    conda-forge
pytables                  3.6.1            py36hb7ec5aa_3    conda-forge
python                    3.6.11          h4d41432_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-igraph             0.9.1            py36h644ed5e_0    conda-forge
python-wget               3.2                        py_0    conda-forge
python-xxhash             2.0.0            py36h8f6f2f9_1    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36h8f6f2f9_0    conda-forge
pyzmq                     22.0.3           py36h7068817_1    conda-forge
qt                        5.9.7                h0c104cb_3    conda-forge
qtconsole                 5.0.3              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
r-base                    3.2.2                         0  
re2                       2021.04.01           h9c3ff4c_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
represent                 1.6.0            py36h8c4c3a4_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
s2n                       1.0.0                h9b69904_0    conda-forge
scanpy                    1.7.1                      py_0    bioconda
scikit-learn              0.22.2.post1     py36hcdab131_0    conda-forge
scipy                     1.5.3            py36h9e8f40b_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
setuptools-scm            6.0.1              pyh44b312d_0    conda-forge
setuptools_scm            6.0.1                hd8ed1ab_0    conda-forge
sinfo                     0.3.1                      py_0    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sklearn-contrib-lightning 0.6.0            py36h284efc9_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.5.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.35.3               h74cdb3f_0    conda-forge
statsmodels               0.12.2           py36h92226af_0    conda-forge
stdlib-list               0.7.0                      py_2    conda-forge
suitesparse               5.7.2                h7a0d4b7_0    conda-forge
tabix                     0.2.6                ha92aebf_0    bioconda
tbb                       2020.2               h4bd325d_4    conda-forge
terminado                 0.9.4            py36h5fab9bb_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
texttable                 1.6.3              pyh9f0ad1d_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py36h8f6f2f9_1    conda-forge
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
trawler                   2.0                  hdfd78af_4    bioconda
typing_extensions         3.7.4.3                    py_0    conda-forge
ucsc-bedtogenepred        377                  h0b8a92a_2    bioconda
ucsc-bigbedtobed          377                  h0b8a92a_2    bioconda
ucsc-genepredtobed        377                  h0b8a92a_4    bioconda
ucsc-genepredtogtf        377                  h0b8a92a_4    bioconda
ucsc-gff3togenepred       377                  h0b8a92a_2    bioconda
ucsc-gtftogenepred        377                  h0b8a92a_4    bioconda
umap-learn                0.5.1            py36h5fab9bb_0    conda-forge
unzip                     6.0                  h7f98852_2    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
velocyto                  0.17.17                  pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
weeder                    2.0                  h7d875b9_5    bioconda
wget                      1.20.1               h22169c7_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py36h5fab9bb_4    conda-forge
xdg                       5.0.1              pyhd8ed1ab_0    conda-forge
xgboost                   1.3.3            py36h5fab9bb_2    conda-forge
xlrd                      1.2.0                    pypi_0    pypi
xlsxwriter                1.3.8              pyhd8ed1ab_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xxhash                    0.8.0                h7f98852_3    conda-forge
xxmotif                   1.6                  h2d50403_2    bioconda
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by KenjiKamimoto-wustl122** [comment]
Although we recommended using conda for python package installation, it is not necessary to use conda for R.
Please install R in another way.

For example, you can download and install R from CRAN. https://cran.r-project.org
In this case, please make sure to uninstall your R in the celloracle's conda environment.

I'm sorry that this point was not clear in our documentation. We will update our documantation soon.
