### ISSUE TITLE
best practices for multiple TFinfo

### ISSUE THREAD

**Issue by celinesin** [morris-lab/CellOracle#51]
I have a set of single cell data where each cluster has it's own set of ATACseq data.  I've already created the TF_to_TG_dictionaries, but now I'm unsure if i should:
1. create multiple celloracle objects (with all the cells), each time loading a different TF_to_TG_dictionary (then throwing away the networks that are not matching the TF_to_TG_dictionary)
2. create an abbreviated celloracle object for each cluster (so a subset of cells), and load the appropriate TF_to_TG_dictionary for each cluster.

I guess my real question is: does the GRN inference step for each cluster use information from the neighboring cells?

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Celine,

Thank you for your question.

The current version of celloracle cannot use multiple TF-TG data, and we have not try either option 1 or 2 you suggested. 
In my opinion, I guess the first option may be better.

The GRN inference itself goes in parallel, so the results does not use any information from the neighboring clusters. However, celloracle use neighbor information in preprocessing steps.
Celloracle preprocessing includes variable gene detection, PCA and knn imputation. These results can be slightly different if you split data in advance. 

Although the current version of celloracle does not support multiple TF-TG data, I think such analysis is very useful. We are planning to implement a function to use cluster-wise TF-TG information in a future version.
