### ISSUE TITLE
Extract information of downstream genes after  TF simulation. 

### ISSUE THREAD

**Issue by annrosebright** [morris-lab/CellOracle#54]
Hi,

Thanks again for making this great tool. After performing the simulation for Specific TF, is there a way to extract the information of the changes in its target genes. Like how the gene expression changed or how many of the downstream genes were affected etc. 
Extracting such information would help us to compare with in vivo studies.

**Comment by KenjiKamimoto-wustl122** [comment]
@annrosebright 

I think #30 will answer your question.

We think your question is very important, but it was not clear in our preprint.
We will discuss this point in our paper, which is hopefully coming soon.

Thank you asking question.

Kenji
