### ISSUE TITLE
Issues finding R packages

### ISSUE THREAD

**Issue by dylanmr** [morris-lab/CellOracle#55]
Hi, 

I am having issues linking R packages to celloracle. I have installed all three packages in R, and then ensured that I have set the correct R path manually using the co.network_analysis.set_R_path function. However, although I can load all three packages manually in R using the specified R path (see picture) 
![image](https://user-images.githubusercontent.com/12213489/125283465-bdebce80-e318-11eb-9931-c50f2aad2fba.png)

the cell oracle test installation module says it fails to load both igraph and linkcomm. 

![image](https://user-images.githubusercontent.com/12213489/125283279-8f6df380-e318-11eb-855f-13b58368be5d.png)

Do you have any suggestions as to how to fix this issue? 

Dylan

**Comment by KenjiKamimoto-wustl122** [comment]
@dylanmr 

I made a notebook to find out the cause of this error.
https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/Trouble_shooting/R_installation_error.ipynb
Please download and try this notebook.

This notebook generates test commands to verify your R library installation.
If you run this command yourself, you will see the error message directly.
Please tell me the content of the error message.

<img width="1036" alt="スクリーンショット 2021-07-12 午前11 23 58" src="https://user-images.githubusercontent.com/42547768/125324071-23ce5b00-e305-11eb-8ceb-0857931fbd80.png">

Kenji

**Comment by dylanmr** [comment]
Hi Kenji, 

Thanks for the fast response. 

This is the message I receive: 

![image](https://user-images.githubusercontent.com/12213489/125400633-6c901d80-e3b2-11eb-9abe-553cd0e173af.png)

**Comment by KenjiKamimoto-wustl122** [comment]
@dylanmr 

According to the error message, it seems that a file in "igraph" package is broken in your PC and causes the error.
Can you uninstall igraph, and then, re-install it?

After reinstalling igraph, please double check that you can import all the libraries.

I hope it helps.

Kenji

**Comment by dylanmr** [comment]
Hi Kenji, 

Thanks for the input. Interestingly enough, if i run this through python in the terminal, everything runs super smoothly.... there must be some issue with my jupyter build that it is looking for the wrong libgfortran build. Ill keep working on it and post here if i find any solution. I will close the issue for now. 

Thanks
Dylan

**Comment by KenjiKamimoto-wustl122** [comment]
@dylanmr 

Thank you for your feedback! 
Please let me know if you find a solution. It will help me a lot!

Kenji
