### ISSUE TITLE
Non-unique gene name for TAIR10_tss_info.bed.txt

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [morris-lab/CellOracle#56]
Hi CellOracle team,

We noticed that the file "TAIR10_tss_info.bed.txt" you provided for Arabidopsis thaliana TAIR10 motif analysis contains gene names that correspond to different genes. For example, gene name "ASG1" is shared between two genes in chromosome 2 and 5, which has TAIR ID "AT2G24100" and "AT5G17640" respectively. The gene annotation of Arabidopsis thaliana often has several genes that share the same common/short names, so please avoid from using short names and use TAIR ID instead. 

I ran through the celloracle tutorial and realize that the Arabidopsis base-GRN information was of no use since the gene names/IDs can not be matched to the singel cell RNA-seq dataset. 

Would be nice if you could provide the file "TAIR10_tss_info.bed.txt" and "CisBP_ver2_Arabidopsis_thaliana.motif2factors.txt" with TAIR ID, or tell me how those files were generated.

Thanks a lot.

Best,
Che-Wei

**Comment by KenjiKamimoto-wustl122** [comment]
@Hsu-Che-Wei 

Thank you for reporting issue. 
We have not noticed this issue in Arabidopsis data. We will update our Arabidopsis data using TAIR ID, instead of gene short name.
I think I can do these tasks in some days. Please wait for a while.

For now, let me share notebook I used to create motif2factors.txt.
https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/02_motif_scan/motif_data_preparation/04_How_to_prepare_CisBP_custom_motif.ipynb


Kenji

**Comment by Hsu-Che-Wei** [comment]
Hi Kenji,

Thanks for the rapid reply. 
Looking forward to the update!

Best,
Che-Wei

**Comment by Hsu-Che-Wei** [comment]
Hi Kenji,

Thank you for the update, but I notice that the updated TSS bed file lacks the fifth column compared to previous one.
Will it affect the analysis?

Best,
Che-Wei

**Comment by KenjiKamimoto-wustl122** [comment]
@Hsu-Che-Wei 


1) TSS bed file

As you noticed, I updated tss bed file for TAIR10. Sorry for the late notification. 
The fifth column is Nan, but I did it on purpose. The fifth column is distance to tss. 
We did not use this information in our analysis. It will not affect any analysis.

If you want to know how I made the tss bed file, Here is the codes. 
https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/01_ATAC-seq_data_processing/option1_scATAC-seq_data_analysis_with_cicero/misc/make_tss_referenece_from_homer_data-Arabidopsis.ipynb



2) Motif database

Also, I made a new motif file for Arabidopsis using TAIR ID. Please use this one.
<img width="628" alt="スクリーンショット 2021-07-27 午後9 32 33" src="https://user-images.githubusercontent.com/42547768/127254393-5386e26a-b0bd-4b1a-80a0-3e8f08f7aceb.png">


3) pre-built base-GRN

I updated base-GRN using TAIR10 promoter DNA-sequence data. 
Tne new base-GRN is available with Celloracle version 0.7.3. 
I updated this file just now (7/27). 

I hope these new data works, but if you find an issue, please let me know.

**Comment by Hsu-Che-Wei** [comment]
Thanks Kenji!
