### ISSUE TITLE
How to output network as common Network File format. 

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [morris-lab/CellOracle#59]
Hi Kenji,

We would like to visualize the fitted network of celloracle in Cytoscape, so we want to know how to extract necessary information from links object.
Would be nice if you can help us out.

Cytoscape accepts following formats:

Simple interaction file (SIF or .sif format)
Nested network format (NNF or .nnf format)
Graph Markup Language (GML or .gml format)
XGMML (extensible graph markup and modelling language).
SBML
BioPAX
GraphML
Delimited text
Excel Workbook (.xls, .xlsx)
Cytoscape.js JSON
Cytoscape CX

Best,
Che-Wei

**Comment by KenjiKamimoto-wustl122** [comment]
@Hsu-Che-Wei 


CellOracle calculates the network for each cluster. 
The dictionary of network data is stored in the `links.links_dict` and `links.filtered_links`.
`links.links_dict` has all network edge before pruning, and `links.filtered_links` has filtered network edge.

1) First, please export the network as a csv file or excel file as follows. Please use `to_

<img width="566" alt="スクリーンショット 2021-08-09 午後4 34 18" src="https://user-images.githubusercontent.com/42547768/128777965-6f5ee13f-dbee-4067-ac66-a75cb3c411e4.png">

You can export excel file like this. You may be asked to install a python library for excel exporting. Please install it if you asked.
<img width="457" alt="スクリーンショット 2021-08-09 午後4 44 52" src="https://user-images.githubusercontent.com/42547768/128778579-69ce9a8c-dd5a-40ba-a9b8-97457b8cf835.png">



2) Then, please import this file to Cytoscape following this instruction.
http://manual.cytoscape.org/en/stable/Node_and_Edge_Column_Data.html

In the future, I will add more options to export network files.
Thanks,
Kenji

**Comment by Hsu-Che-Wei** [comment]
Thanks a lot, that helps!

Best,
Che-Wei
