### ISSUE TITLE
error while installing celloracle 

### ISSUE THREAD

**Issue by xPandasx** [morris-lab/CellOracle#60]
hi! 

i have some problems with one of the commands from your website 
https://morris-lab.github.io/CellOracle.documentation/installation/python_step_by_step_installation.html

everytime i use this command: pip install git+https://github.com/morris-lab/CellOracle.git

it keeps showing me this error: 
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall; and the installation isn't complete. 
I also tried uninstalling "llvmlite" by myself but unfortunately it didn't work. 
I was curious if anybody has encountered similar issues and could help me here

thank you very much!

**Comment by KenjiKamimoto-wustl122** [comment]
@xPandasx 

Can you please try to uninstall ll llvmlite according to this instruction below?
https://github.com/NVIDIA/NeMo/issues/841
And them, please try to install celloracle again.

I hope it works.

Kenji
