### ISSUE TITLE
About the gene expression data input to the regression model

### ISSUE THREAD

**Issue by tingchenlrx** [morris-lab/CellOracle#65]
Hi Kenji,

I haven't worked with CellOracle since September of 2020 and looks like you guys made updates to your code. Thank you so much for your great efforts and sharing this amazing tool!

I read through your [notebook](https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/04_Network_analysis/Network_analysis_with_Seurat_data.ipynb), where you mentioned that Celloracle input should be non-negative values WITHOUT log transformation and scaling. I am wondering if you still use the Seurat R object processed with the SCTransform method as an example here. The “raw_counts” here is the corrected UMI count. If I use `SO = Seurat::NormalizeData()` to normalize the raw counts, I should convert the `SO[[“RNA’]]@data` to the non-logged values and use the non-logged values as the input to the regression model. Am I right? I am confirming this because I noticed you seemed to do some code re-organization (as compared to the version I saw last September). Thank you so much for your time. All the best!

**Comment by KenjiKamimoto-wustl122** [comment]
@tingchenlrx 

Sorry for the delayed response. 
Yes,  if you use `Seurat::NormalizeData()`,  please convert the `SO[[“RNA’]]@data` into non-logged value before starting celloracle analysis.
Or, you can normalize `adata.layers["raw_count"] data`, which is equivalent to `SO@assays$RNA@counts`, using scanpy's data normalization function.

If you use scTransform, you do not need this step and just use `adata.layers["raw_count"] data` for the input of celloracle.

I'm sorry for the lack of clarity in the notebook. I will add this explanation to clarify this point in the notebook.

Kenji

**Comment by tingchenlrx** [comment]
Kenji, apologies for the late reply. Thank you so much for the explanation!
