### ISSUE TITLE
Sankey-plots

### ISSUE THREAD

**Issue by s849** [morris-lab/CellOracle#66]
Hi,

Thanks for generating such a cool tool. I am wondering if the new, current version still supports Sankey-plots? I tried running it with the old function you had (found it on the Youtube tutorial) but I get an error:

#Plot Sankey Diagram
plt.figure(figsize=[5,6])
cl = "louvian_annot"
oracle.plot_mc_results_as_sankey(cluster_use=cl, start=0, end=100)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-105-450dcf660194> in <module>
      2 plt.figure(figsize=[5,6])
      3 cl = "louvian_annot"
----> 4 oracle.plot_mc_results_as_sankey(cluster_use=cl, start=0, end=100)

AttributeError: 'Oracle' object has no attribute 'plot_mc_results_as_sankey'

Thanks!

**Comment by KenjiKamimoto-wustl122** [comment]
@s849 

The Sankey plots functions are still available in the current versions.
But I realized that the function name has typo, causing the error. I'm sorry.
I fixed the typo now. Can you please update celloracle and use celloracle 0.8.3?
I think you will not get the error with celloracle=0.8.3.
