### ISSUE TITLE
AttributeError: module 'xdg' has no attribute 'XDG_CACHE_HOME'

### ISSUE THREAD

**Issue by marvelouscandy** [morris-lab/CellOracle#67]
Hi when I import the celloracle, there's an exception

```
AttributeError: module 'xdg' has no attribute 'XDG_CACHE_HOME'
```

I tried to use xdg version 4.0.0 and 5.0.1, but the issue still remains.

**Comment by marvelouscandy** [comment]
It was issue with XDG package somehow. I uninstalled gimmemotifs and xdg; and reinstalled gimmemotifs, then it worked.

**Comment by KenjiKamimoto-wustl122** [comment]
@marvelouscandy 
Thank you for letting us know the issue and solution. I helps us!

Kenji

**Comment by MehrshadSD** [comment]
Hi Kenji, I have the same issue as I import the celloracle it gives me:
AttributeError: module 'xdg' has no attribute 'XDG_CACHE_HOME'
Can you please help me with that?
