### ISSUE TITLE
Error instantiating Oracle object

### ISSUE THREAD

**Issue by s849** [morris-lab/CellOracle#69]
Hello,

Thanks for developing such a great tool. I have been able to go through the tutorial with the sample data. But I am having an issue running the code with my own data. Particularly when I am instantiating the oracle object, I get the following error:

# Instantiate Oracle object.
oracle.import_anndata_as_raw_count(adata=adata,
                                   cluster_column_name="seurat_clusters",
                                   embedding_name="X_tsne")
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-76-d08fafd26c21> in <module>
      1 # Instantiate Oracle object.
----> 2 oracle.import_anndata_as_raw_count(adata=adata,
      3                                    cluster_column_name="seurat_clusters",
      4                                    embedding_name="X_tsne")

~/opt/anaconda3/lib/python3.8/site-packages/celloracle/trajectory/oracle_core.py in import_anndata_as_raw_count(self, adata, cluster_column_name, embedding_name, transform)
    378 
    379         # update color information
--> 380         col_dict = _get_clustercolor_from_anndata(adata=self.adata,
    381                                                   cluster_name=self.cluster_column_name,
    382                                                   return_as="dict")

~/opt/anaconda3/lib/python3.8/site-packages/celloracle/trajectory/oracle_utility.py in _get_clustercolor_from_anndata(adata, cluster_name, return_as)
    137         return pal
    138 
--> 139     pal = get_palette(adata, cluster_name)
    140     if return_as=="palette":
    141         return pal

~/opt/anaconda3/lib/python3.8/site-packages/celloracle/trajectory/oracle_utility.py in get_palette(adata, cname)
    126 
    127     def get_palette(adata, cname):
--> 128         c = [i.upper() for i in adata.uns[f"{cname}_colors"]]
    129         #c = sns.cubehelix_palette(24)
    130         """

~/opt/anaconda3/lib/python3.8/site-packages/anndata/compat/_overloaded_dict.py in __getitem__(self, key)
     98             return self.overloaded[key].get()
     99         else:
--> 100             return self.data[key]
    101 
    102     def __setitem__(self, key, value):

KeyError: 'seurat_clusters_colors'

I have the Seurat_cluster labels as part of my medatadata, so I am not sure what the problem could be. Any help is appreciated!

Thanks,

**Comment by KenjiKamimoto-wustl122** [comment]
@s849 

I think you have the same issue as  #46. Please take a look at it.

In short, I think you can solve the issue by running the following command before making Oracle object.
`sc.pl.tsne(adata, color="seurat_clusters")`

I hope it helps.

Kenji

**Comment by s849** [comment]
Thanks for responding so quickly. Unfortunately, it didn't work. I run this right before making the object but did not do the trick. Any other ideas?

**Comment by KenjiKamimoto-wustl122** [comment]
@s849  

OK, Can you copy and paste output of the command below?
`print(adata)`
I need to know the data structure of your anndata to find the cause of the error.

**Comment by s849** [comment]
Here it is:

AnnData object with n_obs × n_vars = 1574 × 20765
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'seurat_clusters'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
    obsm: 'X_tsne'
    layers: 'raw_count'

**Comment by KenjiKamimoto-wustl122** [comment]
@s849 

It seems your anndata still does not have color information.

The color information is generated when you make plot for the first time.
Please look at the example below. 
We can see the color information was added to your anndata after making plot.

<img width="671" alt="スクリーンショット 2022-01-17 午後5 45 53" src="https://user-images.githubusercontent.com/42547768/149848432-6b4d6a1c-8f29-481a-b061-7514994406ee.png">

Can you please confirm again that you run the plotting function using the collect cluster name before making Oracle object?
I recommend running the command below.

```
sc.pl.tsne(adata, color="seurat_clusters")
oracle.import_anndata_as_raw_count(adata=adata,
    cluster_column_name="seurat_clusters",
    embedding_name="X_tsne")
```

**Comment by s849** [comment]
Thanks for your comment. I ran the code as suggested but I get the same error. For some reason it does not seem to work.

**Comment by KenjiKamimoto-wustl122** [comment]
@s849 

I have one more idea. 

It seems that the scanpy's plotting function does not generate color map with your cluster data.
It might mean that your clustering data, "seurat_clusters", was recognized as continuous numerical values rather than categorical data. 

1 ) Can you please confirm that your clustering information is visualized as categorical data when you make TSNE plot?
If not, your clustering data is recognized as a continuous value.

2) You can also check the data type of your clustering data as follows. Please try the command below and tell me the output. 
`adata.obs["seurat_clusters"].dtype`

If your clustering is stored as continuous numerical data, you can modify the data type as follows. Please try the following scripts.
```
#  Convert datatype
adata.obs["seurat_clusters"] = adata.obs["seurat_clusters"].astype("object")

# Plot value to make color information
sc.pl.tsne(adata, color="seurat_clusters")

# Make Oracle object
oracle.import_anndata_as_raw_count(adata=adata,
    cluster_column_name="seurat_clusters",
    embedding_name="X_tsne")
```

If this trick works, I guess you have the same issue as #53. Pleas take a look it.

**Comment by s849** [comment]
Hi Kenji,

Thank you for this explanation. I tried the steps but unfortunately, it continues to not work. Do you have any other ideas? Thank you so much for your help!

**Comment by KenjiKamimoto-wustl122** [comment]
@s849 

Can you please share your anndata with me? I look into your data directly. 
 kamimoto[at]wustl.edu (please substitute [at] with @).

**Comment by s849** [comment]
Hi Kenji,

Sure thing. I'll email you the object.

**Comment by rb56** [comment]
Hi I'm having the same problem. I changed the datatype from int to object, but its the same error.
Any tip that worked?
