### ISSUE TITLE
Request: parameter to control the number of parallel processes used by CellOracle functions

### ISSUE THREAD

**Issue by liz-is** [morris-lab/CellOracle#70]
Hi,

I noticed that multiple processes were being used by `oracle.get_links()` and traced this to the use of `n_jobs=-1` [here](https://github.com/morris-lab/CellOracle/blob/063b84252b77f53f80f02cc9c969b7095ac7db42/celloracle/network/regression_models.py#L82) - by default this will use all cores! This is problematic for running CellOracle on an HPC cluster where it's important that the user can control the number of processes used. 

Can you implement a parameter that the user can specify in `oracle.get_links()` that is passed down to control the number of parallel processes?

Edit: I searched and saw that `njobs=-1` is used elsewhere in the code as well, as well as cases where n_jobs is explicitly set to 4 or 8. All of these should really be controllable by the user or will cause problems on shared computational resources.

Thanks!

**Comment by KenjiKamimoto-wustl122** [comment]
@liz-is 

Thank you for using CellOracle. I updated `get_links()` function. Now, It has a n_jobs parameter that control the number of parallel processes. Please look at our tutorial or source code for more information.
file:///Users/k_mbp/Dropbox/NGS/180416_PS1/CellOracle.documentation/notebooks/04_Network_analysis/Network_analysis_with_Paul_etal_2015_data.html#5.-GRN-calculation

In addition, I updated `links.get_score()` function. You can control number of parallel processes with n_jobs parameter.

Kenji

**Comment by liz-is** [comment]
Thanks a lot for the quick update! :)
