### ISSUE TITLE
package ‘rnetcarto’ is not available (for R version 3.6.3)

### ISSUE THREAD

**Issue by kendyhoangucsc** [morris-lab/CellOracle#73]
package ‘rnetcarto’ is not available (for R version 3.6.3), 

is there another way to install this?

**Comment by KenjiKamimoto-wustl122** [comment]
@kendyhoangucsc 

We can install rnetcarto from source file.

Please see our installation instructions for detail.
https://morris-lab.github.io/CellOracle.documentation/installation/index.html#r-requirements

**Comment by kendyhoangucsc** [comment]
Thanks!

**Comment by kendyhoangucsc** [comment]
Also this is kind of related to checking if my installation worked:
when I check to see if my python libraries are installed:

 import celloracle as co
1 package does not meet CellOracle requirement.
 Your h5py version is 2.10.0. Please install h5py>=3.1.0

but when I check my python environment with pip list: h5py                          3.1.0

should I be worried about this?

**Comment by kendyhoangucsc** [comment]
Thanks Kenji!
