### ISSUE TITLE
np.int deprecation warning

### ISSUE THREAD

**Issue by ekernf01** [morris-lab/CellOracle#76]
Hi Kenji, 
When I run `oracle.get_links`, I receive many copies of these warnings:

```
/home/ekernf01/.local/share/r-miniconda/envs/cscb/lib/python3.9/site-packages/celloracle/network/net_core.py:433: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(coefs, np.int):
/home/ekernf01/.local/share/r-miniconda/envs/cscb/lib/python3.9/site-packages/celloracle/network/net_core.py:627: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(df, np.int):
```

I know there are ways to suppress warnings in Python but I am having trouble getting them to work here, and once the warnings are all displayed, it makes my notebooks very large and hard to load. 

Would it be possible to change `np.int` to `int` in lines 433 and 672 of `network/net_core.py`? Thank you for considering!
Eric

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Eric,

Thank you for the feedback! I will change np.int to int.
Also, I'm refactoring some codes to comply with the recent version of numpy.
I'll upload the codes after code testing, it might take a few days.
I'll let you know when it is done. 
Thank you!

Kenji

**Comment by KenjiKamimoto-wustl122** [comment]
Hi Eric,

I updated celloracle to address recent updates to numpy. I also refactored many codes. 
Can you please install and try the new version, celloracle 0.10.1?
I think it will not show any warning now. The codes was tested with python 3.8.
If you get an error or warning, please let me know. I will fix it soon.

Thank you!
Kenji

**Comment by KenjiKamimoto-wustl122** [comment]
FYI, I also updated some codes in the network analysis step.

In the new version, Links.get_score() function was deprecated. Please use Links.get_network_score() instead. Because the new network score calculation is implemented solely in Python code, celloracle no longer requires the R packages. The old function, Links.get_score() still works for a while, but might be removed in the future version.

Please take a look at the new tutorial. https://morris-lab.github.io/CellOracle.documentation/notebooks/04_Network_analysis/Network_analysis_with_Paul_etal_2015_data.html

**Comment by ekernf01** [comment]
I installed the new CO and it is working without warnings. Thank you! 

P.S. I will stop using `links.get_score()` in favor of `get_network_score`.
