### ISSUE TITLE
Issue with take out the files in the docker container

### ISSUE THREAD

**Issue by QianhuiXu** [morris-lab/CellOracle#77]
Hello,

CellOracle is a wonderful tool！

I installed celloracle by using your Docker image(kenjikamimoto126/celloracle_ubuntu). And I created the celloracle conda environment.yaml in the docker container. I ran into an issue with taking out files from docker container.
My command : docker cp e4efc83b8ea1:~/celloracle_environment.yaml /home/qianhui/
Error: No such container:path: e4efc83b8ea1:~/celloracle_environment.yaml
I'm really at a loss as to how to proceed, and any guidance would be much appreciated! 

In addition, could please provide me the celloracle conda environment.yaml from your docker image?
Thank you for your kind help!

**Comment by KenjiKamimoto-wustl122** [comment]
@QianhuiXu 

I'm Kenji, developer of celloracle. Thank you for trying CellOracle.

Sorry, I need more information to know about your issue. 
Can you please give me more information about your issue?
It would be great if you can copy and paste the error message.

Also, we made major update on celloracle.
The docker file is now in the process of update as well. 
I can send you environment.yaml file after finishing updating and testing the new docker image.

**Comment by QianhuiXu** [comment]
Thank you for your swift response!

I had created the the celloracle conda environment.yaml in the docker container and wanted to recreate the celloracle conda environment.
![307353a0f42ba6e3674a3225c1618ae](https://user-images.githubusercontent.com/69391572/163676940-779a532e-f664-47f6-aa17-13f8c6aa4056.png)
(base) qianhui@ubuntu:~$ docker start e4efc83b8ea1
e4efc83b8ea1

(base) qianhui@ubuntu:~$ docker exec -it e4efc83b8ea1 /bin/bash

(celloracle_env) user@e4efc83b8ea1:~$ ls

Anaconda3-2021.05-Linux-x86_64.sh  CellOracle  anaconda3  celloracle_environment.yaml  test.py

(celloracle_env) user@e4efc83b8ea1:~$ 

But I get an error when I wanted to copy the celloracle conda environment.yaml from the docker container to local system
![9ed6fd46c83ab055faa8679076c542a](https://user-images.githubusercontent.com/69391572/163676964-acac8bab-145e-4183-bdf6-1f1bda3c3d1d.png)

(base) qianhui@ubuntu:~$ docker cp e4efc83b8ea1:~/celloracle_environment.yaml /home/qianhui/

Error: No such container:path: e4efc83b8ea1:~/celloracle_environment.yaml

Could you please send the celloracle_conda _environment.yaml file to my email after you finished the new docker image .
My email address is :qianhuixu@zju.edu.cn
Thank you for your kind help!

Best,
Qianhui

**Comment by KenjiKamimoto-wustl122** [comment]
@QianhuiXu 

Sorry for the slow response! 
I updated docker image and I made enviroment.yaml file.
The file was sent to you with email now.

Also, we made some guidance for our docker image. Please check this https://morris-lab.github.io/CellOracle.documentation/installation/docker_additional_information.html
