### ISSUE TITLE
Issue during tfi.scan 

### ISSUE THREAD

**Issue by Ditchburn27** [morris-lab/CellOracle#78]
I am using default_motifs() from gimmemotifs, and keep getting this same issue. I have tried updating gimmemotifs and still get the issue. I have been trying to do this on our labs sever as I am working with a large data set but I did try doing this on my mac but it crashes due to the size of the dataset (264 679 peaks after filtering).  Should mention to that I completely ran through all of the tutorial notebooks using this same conda environment and did not have this issue. 

 from gimmemotifs.motif import default_motifs
 motifs =  default_motifs()

tfi.scan(fpr=0.02,
            motifs=motifs,  
            verbose=True)

It gets to this point and then fails. 

Checking your motifs... Motifs format looks good.

Initiating scanner...

ValueError                                Traceback (most recent call last)
/dd_userdata/usrdat02/userdata/lditchburn/miniconda3/envs/celloracle3/lib/python3.7/site-packages/celloracle/motif_analysis/tfinfo_core.py in scan(self, background_length, fpr, n_cpus, verbose, motifs, TF_evidence_level, TF_formatting, divide)
    365         try:
--> 366             s.set_background(genome=self.ref_genome, size=background_length) # For gimmemotifs ver 14.4
    367         except:

/dd_userdata/usrdat02/userdata/lditchburn/miniconda3/envs/celloracle3/lib/python3.7/site-packages/gimmemotifs/scanner.py in set_background(self, fname, genome, size, nseq, gc, gc_bins)
    891                         fa = RandomGenomicFasta(genome, size, nseq)
--> 892                     cache.set(self.background_hash, (fa, gc_bins))
    893         except sqlite3.DatabaseError:

/dd_userdata/usrdat02/userdata/lditchburn/miniconda3/envs/celloracle3/lib/python3.7/site-packages/diskcache/core.py in set(self, key, value, expire, read, tag, retry)
    771         expire_time = None if expire is None else now + expire
--> 772         size, mode, filename, db_value = self._disk.store(value, read, key=key)
    773         columns = (expire_time, tag, size, mode, filename, db_value)

/dd_userdata/usrdat02/userdata/lditchburn/miniconda3/envs/celloracle3/lib/python3.7/site-packages/diskcache/core.py in store(self, value, read, key)
    220         else:
--> 221             result = pickle.dumps(value, protocol=self.pickle_protocol)
    222

ValueError: pickle protocol must be <= 4

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<timed eval> in <module>

/dd_userdata/usrdat02/userdata/lditchburn/miniconda3/envs/celloracle3/lib/python3.7/site-packages/celloracle/motif_analysis/tfinfo_core.py in scan(self, background_length, fpr, n_cpus, verbose, motifs, TF_evidence_level, TF_formatting, divide)
    366             s.set_background(genome=self.ref_genome, size=background_length) # For gimmemotifs ver 14.4
    367         except:
--> 368             s.set_background(genome=self.ref_genome, length=background_length)# For old gimmemotifs ver 13
    369
    370         #s.set_background(genome="mm9", length=400)

TypeError: set_background() got an unexpected keyword argument 'length'

**Comment by KenjiKamimoto-wustl122** [comment]
@Ditchburn27 

I'm Kenji, developer of celloracle.
Thank you for sharing your issue with us!

I need to know the gimmemotif version to identify the cause of the issue.
On the computational environment you got the error, could you please run the following command and tell me the output?

```
import celloracle as co
co.check_python_requirements()
```

**Comment by Ditchburn27** [comment]
@KenjiKamimoto-wustl122 

Thank you for the reply, my remote access to our sever is currently not working so I am unable to check the computational environment. I'll be back in the office tomorrow and will be able to check then. Sorry that this will drag the issue on for a bit

**Comment by Ditchburn27** [comment]
Okay so this is my computational environment that I am getting this error in. 

     package_name installed_version required_version  requirement_satisfied
0           numpy            1.21.5             auto                   True
1           scipy             1.7.3             auto                   True
2          cython           0.29.28             auto                   True
3           numba            0.55.1           0.49.1                   True
4      matplotlib             3.5.1             auto                   True
5         seaborn            0.11.2             auto                   True
6    scikit-learn             1.0.2             auto                   True
7            h5py             3.6.0            3.1.0                   True
8          pandas             1.3.5            1.0.3                   True
9        velocyto           0.17.17             0.17                   True
10     umap-learn             0.5.2             auto                   True
11        pyarrow             7.0.0             0.17                   True
12           tqdm            4.64.0             4.45                   True
13  python-igraph             0.9.9             auto                   True
14        louvain             0.7.1             auto                   True
15            fa2             0.3.5             auto                   True
16        anndata             0.8.0            0.7.5                   True
17         scanpy             1.9.1              1.6                   True
18         joblib             1.1.0             auto                   True
19       goatools             1.2.3             auto                   True
20       genomepy             0.8.4            0.8.4                   True
21    gimmemotifs            0.14.4           0.14.4                   True

**Comment by Ditchburn27** [comment]
Will close the issue, managed to get past the tfi.scan by creating a new environment and setting it up with the latest release of cell oracle

**Comment by KenjiKamimoto-wustl122** [comment]
@Ditchburn27 
I'm glad that the issue was solved. Thank you for sharing the solution!
