### ISSUE TITLE
Preprint fig 7: duplicated panel?

### ISSUE THREAD

**Issue by concatenize** [morris-lab/CellOracle#8]
Maybe I need a better monitor, but I cannot spot any difference between the "velocity" diagrams for Zfp57 KO and OE. Is it possible you accidentally included the knockout twice?

**Comment by sam-morris** [comment]
Well spotted, thanks! We will update that asap...

**Comment by sam-morris** [comment]
The panel has been corrected and is up on BioRxiv now. Thanks again.
