### ISSUE TITLE
How to deal with batch bias in scRNA preprocess

### ISSUE THREAD

**Issue by wangmhan** [morris-lab/CellOracle#80]
Hi,

Before reconstruction of the GRN network, need to preprocess the scRNA data. You mentioned the log transformed and raw expression values are required. While in my case, I have data from 3 time point. Because the samples are experimented and sequenced in different time, there is batch effect. So that need to correct before integrated them together, I used Seurat IntegrateData.
I want to joint all the data together. I have raw expression values, log transformed and scaled values, and batch corrected values. Do you have any suggestions which should I feed in the adata in the tutorial (https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/03_scRNA-seq_data_preprocessing/scanpy_preprocessing_with_Paul_etal_2015_data.ipynb)? 

Thank you!

**Comment by KenjiKamimoto-wustl122** [comment]
@wangmhan 

1. We recommend using Scanpy to process data as shown in our tutorial.
Although we previously provided data conversion function, `seuratToAnndata`, and it is still available in the current version of celloracle, the function was deprecated now. 
 https://github.com/morris-lab/CellOracle/blob/master/docs/notebooks/04_Network_analysis/Network_analysis_with_Seurat_data.ipynb
Sorry for the inconvenience.

2. The analysis with integrated data has potential problem, and we recommend using non-integrated data or analyzing data independently.

**Comment by wangmhan** [comment]
Thank you for the suggestion! 
Will try it out with either non-integrated or analyze individually.
