### ISSUE TITLE
error when run plot_cartography_scatter_per_cluster function

### ISSUE THREAD

**Issue by wangmhan** [morris-lab/CellOracle#81]
Hi,

I met the error when run function: plot_cartography_scatter_per_cluster.
It shows need to run 'get_score', but the new version is already changed to 'get_network_score'.

**Comment by KenjiKamimoto-wustl122** [comment]
@wangmhan 

The gene cartography analysis is deprecated and removed from our tutorial. 
However, you can still calculate gene cartography score using the old function `get_score()` Please run `links.get_score()` and then try `links.plot_cartography_scatter_per_cluster`

**Comment by wangmhan** [comment]
Thank you for the information, don't know the cartography analysis is deprecated!
