### ISSUE TITLE
Difficult to simulate overexpression

### ISSUE THREAD

**Issue by tiffanyformosa** [morris-lab/CellOracle#83]
CellOracle is very opaque with its upper limit for gene expression, making overexpression hard to do. Would it be possible to autocorrect the simulation to the upper limit if excess overexpression is attempted, or add a column to adata.var that contains the upper limit for each perturbable gene?

**Comment by sam-morris** [comment]
Hi Tiffany, you are most welcome. In the preprint (https://www.biorxiv.org/content/10.1101/2020.02.17.947416v3.full) Fig. 6 legend, we state, "For the simulation of Fos overexpression, we set the Fos expression value at 1.476, which is the maximum value of Fos expression in the imputed gene expression matrix". We recommend this as a starting point as we have not yet experimentally validated any upper limit for overexpression.

**Comment by KenjiKamimoto-wustl122** [comment]
@tiffanyformosa 

Thank you for your feedback.

In our tutorial, we are showing how to check gene expression value, and we are showing the upper limit is 2x of max gene expression value. Please take a look at our tutorial. https://morris-lab.github.io/CellOracle.documentation/notebooks/05_simulation/Gata1_KO_simulation_with_Paul_etal_2015_data.html#3.-In-silico-TF-perturbation-analysis

<img width="771" alt="スクリーンショット 2022-04-28 午後0 33 26" src="https://user-images.githubusercontent.com/42547768/165813688-0ff21870-b258-41e4-8ea7-4af5e4e562ff.png">

As suggested by Sam, we recommend starting with the max value of gene expression for the overexpression simulation.
