### ISSUE TITLE
Request for mm39/GRCm39

### ISSUE THREAD

**Issue by mckellardw** [morris-lab/CellOracle#84]
We have seen considerable improvement with mm39 over mm10 (better alignment rates, 5-10% more reads used in count matrices for some samples!). Would be great to be able to use your tool with our datasets. Thanks!

**Comment by KenjiKamimoto-wustl122** [comment]
@mckellardw 

Thank you for the request! I will update celloracle to be able to use mm39. 
I think it will not take time, and I can do this task in this weekend.

**Comment by KenjiKamimoto-wustl122** [comment]
@mckellardw 
Sorry for taking time, but we updated celloracle and added mm39 data.
Can you please upgrade celloracle to version0.10.7 and try it?
