### ISSUE TITLE
Custom colors for oracle.plot_cluster_whole?

### ISSUE THREAD

**Issue by andrewjkwok** [morris-lab/CellOracle#91]
Hi,

Wanted to quickly ask - is it possible to pass custom colors for my cell clusters (or some categorical variable) for the `oracle.plot_cluster_whole` function after in silico GRN perturbation? 

I've tried passing a `palette` argument as I would in scanpy but that doesn't seem to work, and I can't find within the API documentation what kind of options I might have for the `oracle.plot_cluster_whole` function.

Many thanks in advance,
Andrew

**Comment by KenjiKamimoto-wustl122** [comment]
Hi @andrewjkwok 

I updated cellorale now. In the current version, celloracle=0.10.11, we can update cluster color palette as follows.

`oracle.update_cluster_colors(palette=sns.color_palette("husl", 24))` 


**1) Before changing color.**
<img width="820" alt="スクリーンショット 2022-09-27 午後3 24 25" src="https://user-images.githubusercontent.com/42547768/192877611-0f661104-dd8d-4f7b-bdf0-4948dd1b1c6c.png">

**2) Change color. After running update_cluster_colors function, new color information is used.**
<img width="811" alt="スクリーンショット 2022-09-27 午後3 24 47" src="https://user-images.githubusercontent.com/42547768/192877692-ca70574e-c2f3-4998-a63d-46c0448a178e.png">

I hope it helps.

Kenji

**Comment by andrewjkwok** [comment]
Yes, this helps a lot, thank you!!
