### ISSUE TITLE
Markov chain simulations

### ISSUE THREAD

**Issue by OCKI96** [morris-lab/CellOracle#92]
Hi, I was wondering if I could get some help performing the Markov chain simulation present in the pre-print (Figure 4C). I believe the analysis has been retired from CellOracle but would be very grateful if I could have access to the previous code.  Thanks for your help!

**Comment by KenjiKamimoto-wustl122** [comment]
@OCKI96 

I uploaded previous tutorial notebook that includes Markov simulation.
https://github.com/morris-lab/CellOracle/blob/master/docs/old/210531_Gata1_KO_simulation_with_Paul_etal_2015_data.ipynb
We are currently discontinuing development of the Markov simulation code and moving to a perturbation score metric.
But I think the Markov simulation functions in this notebook still work.
I hope it helps.

Kenji
