### ISSUE TITLE
Error in the gene perturbation simulation

### ISSUE THREAD

**Issue by lingxincheng08** [morris-lab/CellOracle#97]
Hi,
When I am trying to simulate the gene perturbation by function: oracle.simulate_shift(perturb_condition={goi: 0.0},n_propagation=3), I got the following error.
![q1](https://user-images.githubusercontent.com/103924215/213567009-0f89976e-1e6f-468c-9cff-b2e19b00eb88.png)
However, when I check the detail of the gene, it is in the TF target:
![q2](https://user-images.githubusercontent.com/103924215/213567069-eab448f2-eda1-44c1-b951-9ae1887f3910.png)
May I know how to solve it? Thanks so much!

**Comment by KenjiKamimoto-wustl122** [comment]
@lingxincheng08 

It seems that the gene, Aqr, is not in the regulator list (isin_TFdict_regulators False).
CellOracle simulates TF regulation, so the gene should be in the list to simulate its effects. 
But as the error message shows, the gene may not TF or TF motif information is not available for this gene.
